---

- name: Change permissive domain for haproxy
  tags: selinux,haproxy
  selinux_permissive:
    name: haproxy_t
    permissive: true 

- name: move haproxy config file to bastion
  tags: haproxy
  copy:
    src: haproxy.cfg
    dest: /etc/haproxy/haproxy.cfg
    force: yes
    backup: yes

- name: enable haproxy
  tags: haproxy
  systemd:
    enabled: yes
    name: haproxy

- name: Restart haproxy
  tags: haproxy
  systemd:
    state: restarted
    name: haproxy
