---

- name: Load in variables from env.yaml
  tags: haproxy,bastion
  include_vars: env.yaml

- name: Change permissive domain for haproxy
  tags: selinux,haproxy,bastion
  selinux_permissive:
    name: haproxy_t
    permissive: true 

- name: use template to create haproxy config file 
  tags: haproxy,bastion
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    backup: yes
    force: yes

- name: enable haproxy
  tags: haproxy,bastion
  systemd:
    enabled: yes
    name: haproxy

- name: Restart haproxy
  tags: haproxy,bastion
  systemd:
    state: restarted
    name: haproxy
