---

#- name: Add another bin dir to system-wide $PATH.
#  copy:
#    dest: /etc/profile.d/custom-path.sh
#    content: 'PATH=$PATH:{{ my_custom_path_var }}'

- name: echo path
  tags: cluster
  shell: "echo $PATH"
  register: path_check

- name: print results of path check
  tags: cluster
  debug:
    var: path_check.stdout

- name: check who the user is
  tags: cluster
  shell: "whoami"
  register: root_check

- name: print results of checking what user is running tasks
  tags: cluster
  debug:
    var: root_check.stdout

- name: export kube config file
  tags: cluster
  shell: "export KUBECONFIG=/ocpinst/auth/kubeconfig"
  args:
    chdir: /

- name: export kube config file
  tags: cluster
  shell: "export KUBECONFIG=/ocpinst/auth/kubeconfig"
  args:
    chdir: /

- name: check if system admin
  tags: cluster
  command: "oc whoami"
  register: whoami_check
  #until: whoami_check.stdout.find("system:admin") != -1
  #retries: 5
  #delay: 30

- name: print whoami_check results to terminal
  tags: cluster
  debug:
    var: whoami_check.stdout

- name: get csr info
  tags: cluster
  command: oc get csr
  register: csr

- name: print csr info to terminal
  tags: cluster
  debug:
    var: csr.stdout

- name: approve all pending certificates
  tags: cluster
  command: "for i in `oc get csr --no-headers | grep -i pending |  awk '{ print $1 }'`; do oc adm certificate approve $i; done"
  register: csr_approve

- name: print results from csr approval
  tags: cluster
  debug:
    var: csr_approve.stdout

- name: wait 5 minutes
  tags: cluster
  pause:
    minutes: 5

- name: get csr info
  tags: cluster
  command: oc get csr
  register: csr

- name: print csr info to terminal
  tags: cluster
  debug:
    var: csr.stdout

- name: approve all pending certificates
  tags: cluster
  command: for i in `oc get csr --no-headers | grep -i pending |  awk '{ print $1 }'`; do oc adm certificate approve $i; done
  register: csr_approve

- name: print results from csr approval
  tags: cluster
  debug:
    var: csr_approve.stdout