#Will not work as is. Waiting to figure out sshuttle or ProxyCommands to run commands on the bootstrap from bastion jump host.

---
  
#when waiting for bootstrap to come up for the first time, wait for "github.com/openshift/cluster-bootstrap/pkg/start/status.go:66:"

- name: ssh to bootstrap from bastion
  command: ssh core@9.60.87.133

#- name: Wait 30 minutes for bootkube to connect nodes. May take up to 45 minutes.
  #pause: 
    #minutes: 1

#above is for testing. Use below when above works.
#1800

- name: Start checking for bootkube to complete connecting nodes. Checks every 2 minutes.
  command: journalctl -u bootkube.service
  register: bootkube_status
  until: bootkube_status.stdout.find("bootkube.service complete") != -1
  retries: 15
  delay: 1

#above is for testing. Use below when above works.
#retries: 15
#delay: 120