---

- hosts: bastion_server
  become: true
  tasks:
  

#there has to be a way to do this through Ansible. Step 3 page 9
  - name: complete bastion install process

#leaving this until I meet with Filipe
  - name: download software 

#leaving this until I meet with Filipe
  - name: DNS requirements and configuration

#not sure what this instruction step is trying to say. Page 13
  - name: Load Balancer

# Need to edit this script to automate changing port to 8080 and ensure latest versions of OpenShift mirrors
  - name: Create and configure the HTTP server
    script: ~/.git/Ansible-OpenShift-Provisioning/files/shell_scripts/create_http.sh

  - name: Get installer and oc Client Tools
    script: ~/.git/Ansible-OpenShift-Provisioning/files/shell_scripts/get_ocp_installer.sh

##create install-config.yaml file
  - name: create install-config.yaml
    file:
      path: "~/files/install-config.yaml"
      state: touch

##need to use host_vars for <installation_directory>
  - name: Generate the ignition files 1
    shell: ./openshift-install create manifests --dir=<installation_directory>    

##also needs <installation_directory> variable
  - name: Generate the ignition files 2
    shell: ./openshift-install create ignition-configs --dir=<installation_directory>
  
##also needs <installation_directory> variable
  - name: Generate the ignition files 3
    shell: cp <installation_directory>/*.ign /var/www/html/ignition

  - name: Generate the ignition files 4
    shell: chmod 775 /var/www/html/ignition/*.ign

  - name: Prepare the KVM OCP guests
    script: ~/.git/Ansible-OpenShift-Provisioning/files/shell_scripts/prep_kvm_guests.sh
