---

- name: Load in variables from env.yaml
  tags: setup
  include_vars: env.yaml

- name: check if compute-0 already exists
  tags: compute
  community.libvirt.virt:
    name: compute-0
    command: status
  register: compute_0_check
  ignore_errors: yes

- name: print status of compute-0
  tags: compute
  debug: 
    var: compute_0_check

- name: check if compute-1 already exists
  tags: compute
  community.libvirt.virt:
    name: compute-1
    command: status
  register: compute_1_check
  ignore_errors: yes

- name: print status of compute-1
  tags: compute
  debug: 
    var: compute_1_check

- name: install CoreOS on compute-0 node
  tags: compute
  command: |
    virt-install --name compute-0
    --disk size=100 --ram 16000 --cpu host --vcpus 4 
    --os-type linux --os-variant rhel8.0 
    --network network=macvtap-net 
    --location /var/lib/libvirt/images,kernel=rhcos-live-kernel-s390x,initrd=rhcos-live-initramfs.s390x.img 
    --extra-args "rd.neednet=1 coreos.inst=yes coreos.inst.install_dev=vda coreos.live.rootfs_url=http://{{env_ip_bastion}}:8080/bin/rhcos-live-rootfs.s390x.img ip={{env_ip_compute_0}}::{{env_default_gateway}}:{{env_netmask}}:compute-0:enc1:none:1500 nameserver={{env_dns_nameserver}} coreos.inst.ignition_url=http://{{env_ip_bastion}}:8080/ignition/worker.ign" 
    --noautoconsole --wait=-1
  when: compute_0_check.failed == true

- name: pause 15 minutes
  tags: compute
  pause:
    minutes: 15
  when: compute_0_check.failed == true

- name: install CoreOS on compute-1 node
  tags: compute
  command: |
    virt-install --name compute-1
    --disk size=100 --ram 16000 --cpu host --vcpus 4 
    --os-type linux --os-variant rhel8.0 
    --network network=macvtap-net 
    --location /var/lib/libvirt/images,kernel=rhcos-live-kernel-s390x,initrd=rhcos-live-initramfs.s390x.img 
    --extra-args "rd.neednet=1 coreos.inst=yes coreos.inst.install_dev=vda coreos.live.rootfs_url=http://{{env_ip_bastion}}:8080/bin/rhcos-live-rootfs.s390x.img ip={{env_ip_compute_1}}::{{env_default_gateway}}:{{env_netmask}}:compute-1:enc1:none:1500 nameserver={{env_dns_nameserver}} coreos.inst.ignition_url=http://{{env_ip_bastion}}:8080/ignition/worker.ign" 
    --noautoconsole --wait=-1
  when: compute_1_check.failed == true

- name: pause 15 minutes
  tags: compute
  pause:
    minutes: 15
  when: compute_1_check.failed == true