---

- name: check if compute-0 already exists
  tags: compute
  community.libvirt.virt:
    name: compute-0
    command: status
  register: compute-0_check

- name: print status of compute-0
  tags: compute
  debug: 
    var: compute-0_check

- name: check if compute-1 already exists
  tags: compute
  community.libvirt.virt:
    name: compute-1
    command: status
  register: compute-1_check

- name: print status of compute-1
  tags: compute
  debug: 
    var: compute-1_check

- name: install CoreOS on compute-0 node
  tags: compute
  command: |
    virt-install --name compute-0
    --disk size=100 --ram 16000 --cpu host --vcpus 4 
    --os-type linux --os-variant rhel8.0 
    --network network=macvtap-net 
    --location /var/lib/libvirt/images,kernel=rhcos-live-kernel-s390x,initrd=rhcos-live-initramfs.s390x.img 
    --extra-args "rd.neednet=1 coreos.inst=yes coreos.inst.install_dev=vda coreos.live.rootfs_url=http://9.60.87.139:8080/bin/rhcos-live-rootfs.s390x.img ip=9.60.87.135::9.60.86.1:255.255.254.0:compute-0:enc1:none:1500 nameserver=9.60.87.139 coreos.inst.ignition_url=http://9.60.87.139:8080/ignition/worker.ign" 
    --noautoconsole
  when: compute-0_check.failed == true

- name: pause 15 minutes
  tags: compute
  pause:
    minutes: 15
  when: compute-0_check.failed == true

- name: install CoreOS on compute-1 node
  tags: compute
  command: |
    virt-install --name compute-1
    --disk size=100 --ram 16000 --cpu host --vcpus 4 
    --os-type linux --os-variant rhel8.0 
    --network network=macvtap-net 
    --location /var/lib/libvirt/images,kernel=rhcos-live-kernel-s390x,initrd=rhcos-live-initramfs.s390x.img 
    --extra-args "rd.neednet=1 coreos.inst=yes coreos.inst.install_dev=vda coreos.live.rootfs_url=http://9.60.87.139:8080/bin/rhcos-live-rootfs.s390x.img ip=9.60.87.134::9.60.86.1:255.255.254.0:compute-1:enc1:none:1500 nameserver=9.60.87.139 coreos.inst.ignition_url=http://9.60.87.139:8080/ignition/worker.ign" 
    --noautoconsole
  when: compute-1_check.failed == true

- name: pause 15 minutes
  tags: compute
  pause:
    minutes: 15
  when: compute-1_check.failed == true