---
# tasks to check if kvm image file is present and copy if it is not

- hosts: all
  become: true
  tasks:

  - name: check to see if kvm image file is present
    stat:
      path: /tmp/rhel-guest-image-8.3-400.s390x.qcow2
      get_checksum: no
      get_mime: no
      get_attributes: no
    register: os_disk_file

  - name: fail if image file exists
    fail:
      msg: "Image file exists"
    when: os_disk_file is true

  - name: copy kvm image to kvm host(s)
    copy:
      src: rhel-guest-image-8.3-400.s390x.qcow2
      dest: /tmp/rhel-guest-image-8.3-400.s390x.qcow2
      owner: root
      owner: root
      mode: 0644

