---

- hosts: localhost
  tags: setup
  connection: local
  become: false
  gather_facts: no
  vars_files:
    - env.yaml
  vars:
    - ssh_target_ip: "{{ env_ip_kvm_host }}"
  roles:
    - ssh_key_gen
    - ssh_copy_id
    - ssh_agent
    
- hosts: kvm_host
  tags: kvm_host,kvm_prep
  become: true
  vars_files:
    - env.yaml
  vars: # feel free to add more packages as needed
    - packages: ['@server-product-environment','@hardware-monitoring','@network-file-system-client','@remote-system-management',
                '@headless-management','@system-tools','libvirt-devel','libvirt-daemon-kvm','qemu-kvm','virt-manager','genisoimage',
                'libvirt-daemon-config-network','libvirt-client','qemu-img','virt-install','virt-viewer','libvirt-daemon-kvm','libvirt'] 
  roles:
    - check_ssh
    - attach_subscription
    - install_packages
    - set_selinux_permissive
    - enable_packages
    - macvtap
    - create_bastion

- hosts: localhost
  tags: bastion
  connection: local
  become: false
  gather_facts: no
  vars_files:
    - env.yaml
  vars:
    - ssh_target_ip: "{{ env_ip_bastion }}"
  roles:
    - ssh_copy_id

- hosts: bastion
  tags: bastion
  become: true
  vars_files:
    - env.yaml
  vars: # feel free to add more packages as needed
    - packages: ['haproxy','httpd','bind','bind-utils','expect','firewalld','mod_ssl']
  roles:
    - check_ssh
    - attach_subscription
    - install_packages #RHEL subscription already attached
    - ssh-ocp-key-gen # SSH key for bastion to connect to nodes
    - set_selinux_permissive
    - set_firewall
    - dns
    - haproxy
    - httpd
    - get-ocp

- hosts: kvm_host
  tags: kvm_host,create_nodes
  become: true
  gather_facts: no
  vars_files:
    - env.yaml
  roles:
    - prep_kvm_guests
    - create_bootstrap
    - create_control_nodes
    - create_compute_nodes