---

- hosts: localhost
  tags: setup
  connection: local
  become: false
  gather_facts: no
  vars_files:
    - env.yaml
  vars:
    - ssh_target_ip: "{{ env.ip.kvm }}"
  roles:
    - ssh_key_gen
    - ssh_copy_id
    - ssh_agent
    
- hosts: kvm_host
  tags: kvm_host, kvm_prep
  become: true
  vars_files:
    - env.yaml
  vars: 
    - packages: "{{ env.pkgs.kvm}}"
  roles:
    - check_ssh
    - attach_subscription
    - install_packages
    - set_selinux_permissive
    - macvtap
    - create_bastion

- hosts: localhost
  tags: bastion
  connection: local
  become: false
  gather_facts: no
  vars_files:
    - env.yaml
  vars:
    - ssh_target_ip: "{{ env.ip.bastion }}"
  roles:
    - ssh_copy_id

- hosts: bastion
  tags: bastion
  become: true
  vars_files:
    - env.yaml
  vars:
    - packages: "{{env.pkgs.bastion}}"
  roles:
    - check_ssh
    - attach_subscription
    - install_packages
    - ssh_ocp_key_gen
    - set_selinux_permissive
    - set_firewall
    - dns
    - check_dns
    - haproxy
    - httpd
    - get_ocp

- hosts: kvm_host
  tags: kvm_host, create_nodes
  become: true
  gather_facts: no
  vars_files:
    - env.yaml
  roles:
    - prep_kvm_guests
    - create_bootstrap
    - create_control_nodes
    - create_compute_nodes

- hosts: bastion
  tags: verification, bastion
  become: true
  gather_facts: yes
  vars_files:
    - env.yaml
  roles:
    - wait_for_bootstrap
    - approve_certs
    - check_nodes
    - wait_for_cluster_operators
    - wait_for_install_complete