---

#- hosts: workstation
#  become: true
#  roles:
#  vars: "reminder to add vars for remote host to copy ssh key to, kvm_host in this case"
#  - install_ansible_galaxy
#  - update_repo_index
#  - ssh_key_gen
#  - copy_ssh_key

- hosts: kvm_host
  become: true
  roles:
  #- install_packages
  #- macvtap
  #- create_bastion

#- hosts: workstation
#  become: true
#  roles:
#  vars: "reminder to add vars for remote host to copy ssh key to, bastion in this case"
#  - copy_ssh_key

- hosts: bastion_server
  become: true
  roles:
  #- set_selinux_permissive
  - haproxy
  - httpd
  - get-ocp

- hosts: kvm_host
  become: true
  roles:
  - prep_kvm_guests
  - create_bootstrap

- hosts: kvm_host
  become: true
  roles:
  - create_control_nodes
  - create_compute_nodes

#- hosts: bootstrap_server
#  become: true
#  roles:
#  - verify_bootstrap

#- hosts: bastion_server
#  become: true
#  roles:
#  - remove_bootstrap
#  - approve_certs
#  - verify_installation
  
