---

- hosts: localhost
  connection: local
  become: false
  gather_facts: no
  vars_files:
    - env.yaml
  vars:
    - ssh_target_ip: "{{ env_ip_kvm_host }}"
  roles:
    - ansible_setup
    - ssh_key_gen
    - ssh_copy_id

- hosts: kvm_host
  become: true
  vars_files:
    - env.yaml
  vars:
    - packages: [ 'libvirt-devel', 'libvirt-daemon-kvm', 'qemu-kvm', 'virt-manager', 'libvirt-daemon-config-network', 'libvirt-client', 'qemu-img', 'libvirt' ]
  roles:
    - check_ssh
    - install_packages
    - set_selinux_permissive
    - enable_packages
    - macvtap
    - mount_rhel
    - create_bastion

- hosts: localhost
  connection: local
  become: false
  gather_facts: no
  vars: 
    - ssh_target_ip: "{{ env_ip_bastion }}"
  roles:
    - ssh_copy_id

- hosts: bastion
  become: true
  vars: 
    - packages: [ 'haproxy', 'httpd', 'mod_ssl', 'bind', 'bind_utils' ]
  roles:
    - check_ssh
    - install_packages
    - set_firewall
    - set_selinux_permissive
    - dns
    - haproxy
    - httpd
    - get-ocp

- hosts: kvm_host
  become: true
  gather_facts: no
  roles:
    - prep_kvm_guests
    - create_bootstrap
    - create_control_nodes
    - create_compute_nodes

#- hosts: localhost
  #connection: local
  #become: false
  #gather_facts: yes
  #roles:
  #- ssh_config_jump

#- hosts: bastion
  #become: true
  #gather_facts: no
  #roles:
  #- wait_for_bootkube