---

- hosts: localhost
  become: true
  vars_prompt:
    - name: Confirm start of OpenShift cluster automated provisioning process.
      prompt: "Type 'YES' to confirm automated provisioning of OpenShift cluster."
      default: 'NO'
      private: no
      when: confirmation != "YES"
  pre_tasks:
    - name: "Check Confirmation"
      fail: msg="Exiting... You must type 'YES' to continue."
      when: confirmation != "YES"
  vars:
    - [ package_1: ansible_galaxy, package_2: sshpass, package_3: ssh-keygen, package_4: ssh-copy-id ]
    - remote_host_ip: host
    #- other vars needed: ssh_key_filename, remote_machine_password, remote_machine_username, remote_host_ip
  roles:
    #- ansible_setup (check vars file for undefined vars, run ansible_setup, and fill necessary env vars files)
    - install_packages
    #- ssh_key_gen
    #- ssh_copy_id

- hosts: kvm_host
  become: true
  vars:
    - [ package_1: libvirt, package_2: libvirt-devel, package_3: libvirt-daemon-kvm, package_4: qemu-kvm, package_5: virt-manager, package_6: libvirt-daemon-config-network, package_7: libvirt-client, package_8: qemu-img ]
  roles:
    #- check_ssh
    - install_packages
    #- enable libvirt
    - macvtap
    - create_bastion #(reminder to eventually use boot instructions)

- hosts: localhost
  become: true
  gather_facts: no
  vars: 
    - target: bastion_server
  roles:
    - ssh_copy_id

- hosts: bastion_server
  become: true
  vars: 
    - [ package_1: haproxy, package_2: httpd, package_3: mod_ssl, package_4: bind, package_5: bind_utils ] #reminder that "bind" is called "named" after install
  roles:
  #- firewall (whatever that may be)
  #- set_selinux_permissive
  - dns
  - haproxy
  - httpd
  - get-ocp

- hosts: kvm_host
  become: true
  gather_facts: no
  roles:
  - prep_kvm_guests
  - create_bootstrap
  - create_control_nodes
  - create_compute_nodes

#- hosts: localhost
  #become: true
  #gather_facts: yes
  #roles:
  #- ssh_config_jump

#- hosts: bastion_server
  #become: true
  #gather_facts: no
  #roles:
  #- wait_for_bootkube
#  - remove_bootstrap
#  - approve_certs
#  - verify_installation
  
