---

- hosts: localhost
  tags: localhost, prep
  connection: local
  become: false
  gather_facts: no
  vars_prompt:
    - name: vault_pass
      prompt: Please provide a secure password to be used for encrypting your sensitive files in Ansible
      private: yes
      unsafe: yes # this just means you can use special characters. The password is safe.

    - tasks:
      - name: install Ansible dependencies and packages
        shell: ansible-setup-mac.sh
      
