---

#needed:
#- shutdown and destroy bootstrap, control, and compute nodes
#- delete /ocpinst/
#- delete ssh keys from known hosts in bastion and delete ssh keys from ~/.ssh/id_rsa* 
#- delete ssh key from roles/get-ocp/files/ocp_ssh_pub

# Use the "full" tag when running this playbook to reset your installation back to the point where no VMs were running on the KVM host. After you run this playbook, to start back up from that point, run the main.yaml playbook with "--tags 'bastionvm,bastion,create_nodes'"
- hosts: kvm_host
  tags: full
  become: true
  gather_facts: no
  vars:
    - vms: ['bastion', bootstrap', 'control-0', 'control-1', 'control-2', 'compute-0', 'compute-1']
  roles:
    - teardown_vms

# Use the "partial" tag when running this playbook to reset your installation back to the point where just the bastion node was running on the KVM host. After you run this playbook, to start back up from that point, run the main.yaml playbook with "--tags 'bastion,create_nodes'"
- hosts: bastion
  tags: partial
  become: true
  gather_facts: no
    - reset_files

- hosts: kvm_host
  tags: partial
  become: true
  gather_facts: no
  vars:
    - vms: ['bootstrap', 'control-0', 'control-1', 'control-2', 'compute-0', 'compute-1']
  roles:
    - teardown_vms
