---

# Use the "full_teardown" tag when running this playbook to reset your installation back to the point where no VMs were running on the KVM host. 
# After you run this playbook, run the main playbook from the beginning with no tags ("ansible-playbook main.yaml --ask-become-pass")

- hosts: kvm_host
  tags: full_teardown
  become: true
  gather_facts: no
  vars:
    - bastion_teardown: yes
  vars_files:
    - env.yaml
  post_tasks:
    - name: Capture files to delete
      find:
        paths: /var/lib/libvirt/images
        file_type: file
        excludes: 
          - "lost+found"
      register: found_files
    - name: delete files in /var/lib/libvirt/images except for lost+found
      file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ found_files['files'] }}"
    - name: remove local workstation from KVM hosts' authorized_keys file
      file:
        path: "~/.ssh/authorized_keys"
        state: absent
  roles:
    - teardown_vms

- hosts: localhost
  tags: full_teardown
  connection: local
  become: false
  gather_facts: no
  vars:
    - files_to_reset: ['~/.ssh/ansible','~/.ssh/ansible.pub'] # feel free to add as needed
  vars_files:
    - env.yaml
  pre_tasks:
    - name: remove bastion from localhost's known_hosts file
      lineinfile:
        path: "~/.ssh/known_hosts"
        regexp: "{{ env.ip.bastion}}"
        state: absent
    - name: remove KVM host from localhost's known_hosts file
      lineinfile:
        path: "~/.ssh/known_hosts"
        regexp: "{{ env.ip.kvm}}"
        state: absent
  roles:
  - reset_files

# Use the "partial_teardown" tag when running this playbook to reset your installation back to the point where just the bastion node was running on the KVM host. 
# After you run this playbook, to start back up from that point, run the main.yaml playbook with "--tags 'bastion,create_nodes,verification'"

- hosts: localhost
  tags: partial_teardown
  connection: local
  become: false
  gather_facts: no
  vars_files:
    - env.yaml
  tasks:
    - name: remove bastion from localhost's known_hosts file
      lineinfile:
        path: "~/.ssh/known_hosts"
        regexp: "{{ env.ip.bastion}}"
        state: absent

- hosts: bastion
  tags: partial_teardown
  become: true
  gather_facts: no
  vars:
    - files_to_reset: ['~/.ssh/known_hosts', '~/.ssh/id_rsa','~/.ssh/id_rsa.pub','/ocpinst'] # feel free to add as needed
  vars_files:
    - env.yaml
  roles:
    - reset_files

- hosts: kvm_host
  tags: partial_teardown
  become: true
  gather_facts: no
  vars:
    - bastion_teardown: no
  vars_files:
    - env.yaml
  roles:
    - teardown_vms