---

# Use the "full" tag when running this playbook to reset your installation back to the point where no VMs were running on the KVM host. Extra RHEL apps will not be torn down.
# After you run this playbook, run the main playbook from the beginning with no tags ("ansible-playbook main.yaml --ask-become-pass")

- hosts: kvm_host
  tags: full
  become: true
  gather_facts: no
  vars:
    - bastion_teardown: yes
  vars_files:
    - env.yaml
  post_tasks:
    - name: Capture files to delete
      find:
        paths: /var/lib/libvirt/images
        file_type: file
        excludes: 
          - "lost+found"
      register: found_files
    - name: delete files in /var/lib/libvirt/images except for lost+found
      file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ found_files['files'] }}"
    - name: remove local workstation from KVM hosts' authorized_keys file
      file:
        path: "~/.ssh/authorized_keys"
        state: absent
  roles:
    - teardown_vms

- hosts: workstation
  tags: full
  connection: local
  become: false
  gather_facts: no
  vars:
    - files_to_reset: ['~/.ssh/ansible','~/.ssh/ansible.pub'] # feel free to add as needed
  vars_files:
    - env.yaml
  pre_tasks:
    - name: remove bastion from workstation's known_hosts file
      lineinfile:
        path: "~/.ssh/known_hosts"
        regexp: "{{ env.ip.bastion}}"
        state: absent
    - name: remove KVM host from workstation's known_hosts file
      lineinfile:
        path: "~/.ssh/known_hosts"
        regexp: "{{ env.ip.kvm}}"
        state: absent
  roles:
  - reset_files

# Use the "partial" tag when running this playbook to reset your installation back to the point where just the bastion node was running on the KVM host. If extra RHEL VM apps were created, they will not be torn down.
# After you run this playbook, to start back up from that point, run the main.yaml playbook with "--tags 'get_ocp,create_nodes,verification'"

- hosts: bastion
  tags: partial
  become: true
  gather_facts: no
  vars:
    - files_to_reset: ['/home/{{ env.access.login.bastion.user }}/ocpinst'] # feel free to add as needed
  vars_files:
    - env.yaml
  roles:
    - reset_files

- hosts: kvm_host
  tags: partial
  become: true
  gather_facts: no
  vars:
    - bastion_teardown: no
  vars_files:
    - env.yaml
  roles:
    - teardown_vms

# Use the "app" tag with teardown.yaml to teardown all extra RHEL VM apps running on the KVM host.
# To recreate them, run the main playbook with "--tags app"

- hosts: workstation
  tags: app
  connection: local
  become: false
  gather_facts: no
  vars_files:
    - env.yaml
  tasks:
    - name: remove apps from workstation's known_hosts file for idempotency if created
      lineinfile:
        path: "~/.ssh/known_hosts"
        regexp: "{{ env.ip.app[i] }}"
        state: absent
      with_sequence: start=0 end={{(env.hostname.app | length) - 1}} stride=1
      loop_control:
        extended: yes
        index_var: i
      when: env.ip.app is defined
    
- hosts: kvm_host
  tags: app
  become: true
  gather_facts: no
  vars_files:
    - env.yaml
  tasks:
    - name: Destroy running app nodes. Expect ignored errors if some VMs are already destroyed.
      community.libvirt.virt:
        name: "{{ item }}"
        command: destroy
      loop: "{{ env.hostname.app }}"
      ignore_errors: yes

    - name: Undefine remaining app nodes. Expect ignored errors if some VMs are already undefined.
      community.libvirt.virt:
        name: "{{ item }}"
        command: undefine
      loop: "{{ env.hostname.app }}"
      ignore_errors: yes

    - name: Remove apps qcow2 files for idempotency
      tags: create_extra_rhel
      file:
        path: /var/lib/libvirt/images/{{ item }}.qcow2
        state: absent
      loop: "{{env.hostname.app}}"

    - name: Remove seeds for idempotency
      tags: create_extra_rhel
      file:
        path: /var/lib/libvirt/images/{{ item }}-seed.img
        state: absent
      loop: "{{env.hostname.app}}"

    - name: Remove app meta data for idempotency
      tags: create_extra_rhel
      file:
        path: /var/lib/libvirt/images/tmp/{{ item }}/meta-data
        state: absent
      loop: "{{ env.hostname.app }}"

    - name: Remove app user data for idempotency
      tags: create_extra_rhel
      file:
        path: /var/lib/libvirt/images/tmp/{{ item }}/user-data
        state: absent
      loop: "{{ env.hostname.app }}"

    - name: Remove app network config data for idempotency
      tags: create_extra_rhel
      file:
        path: /var/lib/libvirt/images/tmp/{{ item }}/network-config
        state: absent
      loop: "{{ env.hostname.app }}"