---

- name: Load in variables from env.yaml
  tags: prep_kvm_guests
  include_vars: env.yaml

- name: Check to see if kernel already exists on KVM host
  tags: prep_kvm_guests
  stat:
    path: /var/lib/libvirt/images/rhcos-live-kernel-s390x
  register: kernel_check

- name: Get Red Hat CoreOS kernel
  tags: prep_kvm_guests
  get_url:
    url: "{{ env.coreos.kernel }}"
    dest: /var/lib/libvirt/images/rhcos-live-kernel-s390x
    mode: '0755'
    force: yes
  when: kernel_check.stat.exists == false

- name: Check to see if initramfs already exists on KVM host
  tags: prep_kvm_guests
  stat:
    path: /var/lib/libvirt/images/rhcos-live-initramfs.s390x.img
  register: initramfs_check

- name: Get Red Hat CoreOS initramfs
  tags: prep_kvm_guests
  get_url:
    url: "{{ env.coreos.initramfs }}"
    dest: /var/lib/libvirt/images/rhcos-live-initramfs.s390x.img
    mode: '0755'
    force: yes
  when: initramfs_check.stat.exists == false

- name: Add admin user to qemu and libvirt groups
  tags: prep_kvm_guests
  become: true
  command: usermod -aG {{item}} {{ env.access.login.kvm.user }}
  loop:
    - libvirt
    - qemu