---

- name: Load in variables from env.yaml
  tags: kvm_host
  include_vars: env.yaml

- name: get rhcos kernel
  tags: kvm_host
  get_url:
    url: "{{ env_rhcos_kernel }}"
    dest: /var/lib/libvirt/images/rhcos-live-kernel-s390x
    mode: '0755'
    force: yes

- name: get rhcos initramfs image
  tags: kvm_host
  get_url:
    url: "{{ env_rhcos_initramfs }}"
    dest: /var/lib/libvirt/images/rhcos-live-initramfs.s390x.img
    mode: '0755'
    force: yes