---

- name: Approving all pending CSR
  tags: approve_certs
  environment:
    KUBECONFIG: "/ocpinst/auth/kubeconfig"
  shell: |
    /ocpinst/oc get csr | awk '{print $1'} | grep -v NAME | xargs /ocpinst/oc adm certificate approve
  register: csr_approved_1
  ignore_errors: yes

- name: viewing first csr approved
  tags: approve_certs
  debug:
    msg: "{{csr_approved_1.stdout_lines}}"

- name: pause to let new certificates needing approval to generate
  tags: approve_certs
  pause: 
    seconds: 30

- name: Second round approving all pending CSR
  tags: approve_certs
  environment:
    KUBECONFIG: "/ocpinst/auth/kubeconfig"
  shell: |
    /ocpinst/oc get csr | awk '{print $1'} | grep -v NAME | xargs /ocpinst/oc adm certificate approve
  register: csr_approved_2
  ignore_errors: yes

- name: viewing second csr approved
  tags: approve_certs
  debug:
    msg: "{{csr_approved_2.stdout_lines}}"

- name: pause to let new certificates needing approval to generate
  tags: approve_certs
  pause: 
    seconds: 30

- name: Third round approving all pending CSR
  tags: approve_certs
  environment:
    KUBECONFIG: "/ocpinst/auth/kubeconfig"
  shell: |
    /ocpinst/oc get csr | awk '{print $1'} | grep -v NAME | xargs /ocpinst/oc adm certificate approve
  register: csr_approved_3
  ignore_errors: yes

- name: viewing third csr approved
  tags: approve_certs
  debug:
    msg: "{{csr_approved_3.stdout_lines}}"

- name: pause to let new certificates needing approval to generate
  tags: approve_certs
  pause: 
    seconds: 30

- name: Fourth round approving all pending CSR
  tags: approve_certs
  environment:
    KUBECONFIG: "/ocpinst/auth/kubeconfig"
  shell: |
    /ocpinst/oc get csr | awk '{print $1'} | grep -v NAME | xargs /ocpinst/oc adm certificate approve
  register: csr_approved_4
  ignore_errors: yes

- name: viewing fourth csr approved
  tags: approve_certs
  debug:
    msg: "{{csr_approved_4.stdout_lines}}"

- name: pause to let new certificates needing approval to generate
  tags: approve_certs
  pause: 
    seconds: 30

- name: Fifth round approving all pending CSR
  tags: approve_certs
  environment:
    KUBECONFIG: "/ocpinst/auth/kubeconfig"
  shell: |
    /ocpinst/oc get csr | awk '{print $1'} | grep -v NAME | xargs /ocpinst/oc adm certificate approve
  register: csr_approved_5
  ignore_errors: yes

- name: viewing fifth csr approved
  tags: approve_certs
  debug:
    msg: "{{csr_approved_4.stdout_lines}}"