---

- name: Check SSH to remote hosts works
  tags: check_ssh, ssh
  shell: "hostname; id"
  register: ssh_connection_test
  failed_when: ssh_connection_test.rc != 0

- name: Print the connectivity test results
  tags: check_ssh, ssh
  debug:
    var: ssh_connection_test.stdout_lines