---

- name: check ssh to remote hosts works
  shell: "hostname; id"
  register: ssh_connection_test
  failed_when: ssh_connection_test.rc != 0

- name: print the connectivity test results
  debug:
    var: ssh_connection_test.stdout_lines