---

- name: Start and enable libvirt
  tags: macvtap
  service:
    name: libvirtd
    enabled: yes
    state: started

- name: Set up macvtap bridge configuration xml from template to KVM host
  tags: macvtap
  community.libvirt.virt_net:
    command: define
    name: macvtap-net
    xml: "{{ lookup ('template', 'macvtap.xml.j2') }}"

- name: Start macvtap-net bridge
  tags: macvtap
  community.libvirt.virt_net:
    command: start
    name: macvtap-net

- name: Set macvtap-net bridge to autostart
  tags: macvtap
  community.libvirt.virt_net:
    autostart: yes
    name: macvtap-net