---

- hosts: bastion_server
  become: true
  tasks:
  
  - name: start bastion install process
    community.libvirt.virt:
      name: bastion
      memory: 4096
      vcpus: 2
      disk size: 30
      cdrom: /var/lib/libvirt/images/rhel83.iso
      accelerate: yes
      import: yes
      network: network=macvtap-net
      extra-args: ""ip=9.60.87.139::9.60.86.1:255.255.254.0:bastion.distribution.ocpz.wsclab.endicott.ibm>
      location: /rhcos-install
      qemu-commandline: "-drive if=none,id=ignition,format=raw,file=/var/lib/libvirt/images/rhel83.iso,re>
      noautoconsole: yes

##- name: install haproxy
##  dnf:
##  - haproxy

  - name: move haproxy config file to bastion
    copy:
      src: roles/bastion_server/bastion_s390x/templates/haproxy.cfg.j2
      dest: /etc/haproxy/haproxy.cfg

##- name: update repository index
##   dnf:
##     update_cache: yes

##- name: install httpd
##  dnf:
##    name: httpd
##    state: latest

  - name: Ensure the default Apache port is 8080
    replace:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^Listen 80 '
      replace: 'Listen 8080'
      backup: yes

  - name: Ensure the SSL default port is 4443
    replace:
      path: /etc/httpd/conf.d/ssl.conf
      regexp: '^Listen 443 https'
      replace: 'Listen 4443 https'
      backup: yes

  - name: restart httpd to reflect changes to port
    service:
      name: httpd
      state: restarted

  - name: Allow all access to tcp port 8080
    community.general.ufw:
      rule: allow
      port: '8080'
      proto: tcp

  - name: Allow all access to tcp port 80
    community.general.ufw:
      rule: allow
      port: '80'
      proto: tcp

  - name: Allow all access to tcp port 443
    community.general.ufw:
      rule: allow
      port: '443'
      proto: tcp

  - name: Allow all access to tcp port 4443
    community.general.ufw:
      rule: allow
      port: '4443'
      proto: tcp

  - name: create directory bin for mirrors
    file:
      path: /var/www/html/bin
      state: directory
      mode: '0755'

  - name: create directory bootstrap for mirrors
    file:
      path: /var/www/html/bootstrap
      state: directory
      mode: '0755'

  - name: get mirrors 1
    get_url:
      url: https://mirror.openshift.com/pub/openshift-v4/s390x/dependencies/rhcos/latest/latest/rhcos-liv>
      dest: /var/www/html/bin
      remote_src: yes
      mode: '0755'

  - name: get mirrors 2
    get_url:
      url: https://mirror.openshift.com/pub/openshift-v4/s390x/dependencies/rhcos/latest/latest/rhcos-liv>
      dest: /var/www/html/bin
      remote_src: yes
      mode: '0755'

  - name: get mirrors 3
    get_url:
      url: https://mirror.openshift.com/pub/openshift-v4/s390x/dependencies/rhcos/latest/latest/rhcos-liv>
      dest: /var/www/html/bin
      remote_src: yes
      mode: '0755'

  - name: check to make sure httpd is started
    service:
      name: httpd
      state: started

  - name: check httpd status
    service:
      state: started
      name: httpd

  - name: change mirror 1 file name
    command: mv /var/www/html/bin/rhcos-live-kernel-s390x /var/www/html/bin/rhcos-kernel

  - name: change mirror 2 file name
    command: mv /var/www/html/bin/rhcos-live-initramfs.s390x.img /var/www/html/bin/rhcos-initramfs.img

  - name: change mirror 3 file name
    command: mv /var/www/html/bin/rhcos-live-rootfs.s390x.img /var/www/html/bin/rhcos-rootfs.img
