---

- hosts: bastion_server
  become: true
  tasks:

  - name: start bastion install process
    community.libvirt.virt:
      name: bastion 
      memory: 8172 
      vcpus: 4 
      disk size: 30 
      cdrom: /var/lib/libvirt/images/rhel83.iso
      accelerate: yes 
      import: yes 
      network: network=macvtap-net 
      extra-args: ""ip=9.60.87.139::9.60.86.1:255.255.254.0:bastion.distribution.ocpz.wsclab.endicott.ibm.com::none nameserver=9.60.70.82 inst.repo=http://9.60.86.81/linux/s390x/boot/rel/8.3/ ipv6.disable=1"
      location: /rhcos-install
      qemu-commandline: "-drive if=none,id=ignition,format=raw,file=/var/lib/libvirt/images/rhel83.iso,readonly=on -device virtio-blk,serial=ignition,drive=ignition" 
      noautoconsole: yes
