---

- name: check to see if .vault_pass.txt exists already
  stat:
    path: .vault_pass.txt
  register: vault_pass_check

- name: delete .vault_pass.txt if it exists already to ensure idempotence 
  file:
    path: .vault_pass.txt
    state: absent
  when: vault_pass_check.stat.exists

- name: fill .vault_pass.txt with user-provided password
  lineinfile: 
    path: .vault_pass.txt
    state: present
    create: yes
    line: "{{ vault_pass }}"