---

- name: Create ssh config file (or add to an exsting file) to if network mode is NAT
  tags: ssh_copy_id, ssh
  ansible.builtin.blockinfile:
    path: ~/.ssh/config
    backup: true
    create: true
    mode: '0644'
    block: |
      Host {{env.bastion.vm_name }} 
        HostName {{ env.jumphost.ip }}
        User {{ env.jumphost.user }}
        IdentityFile {{ env.jumphost.path_to_keypair }} 
      Host {{ env.bastion.networking.ip }}
        HostName {{ env.bastion.networking.ip }} 
        User {{ env.bastion.access.user }}
        IdentityFile ~/.ssh/{{ env.ansible_key_name }}
        ProxyJump {{ env.bastion.vm_name }} 
