---

#Uncomment once we have a RHEL license
#- name: download RHEL ISO image to KVM
#  get_url:
#      url: {{ RHEL ISO URL }}
#      dest: /var/lib/libvirt/images/rhel83.iso
#      mode: '0775'

#- name: Unzip RHEL iso
#  ansible.builtin.unarchive:
#    src: https://mirror.redhat.com/rhel/latest/latest/RHEL-8.3.0-20201009.2-s390x-dvd1.iso
#    dest: /var/lib/libvirt/images/rhel83.iso
#    remote_src: yes

  #- name: create install mount directory
  #  command: mkdir /rhcos-install

  #- name: mount rhcos install directory
  #  command: mount -o loop /var/lib/libvirt/images/rhel83.iso /rhcos-install/

#  - name: virtualize bastion server
#    command: qemu-img create -f qcow2 -b /var/lib/libvirt/images/rhcos-qemu.s390x.qcow2 /var/lib/libvirt/images/bastion.qcow2 30G

- name: Load in variables from env.yaml
  tags: kvm_host, bastionvm
  include_vars: env.yaml

- name: check if bastion already exists
  tags: kvm_host, bastionvm
  community.libvirt.virt:
    name: bastion
    command: status
  register: bastion_check
  ignore_errors: true

- name: print status of bastion
  tags: kvm_host, bastionvm
  debug: 
    var: bastion_check

- name: start bastion install
  tags: kvm_host, bastionvm
  command: virt-install --connect qemu:///system --name bastion --memory 8192 --vcpus 4 --disk size=30 --cdrom /var/lib/libvirt/images/rhel83.iso --accelerate --import --network network=macvtap-net --extra-args "ip={{env_ip_bastion}}::{{env_default_gateway}}:{{env_netmask}}:bastion::none nameserver={{env_dns_nameserver}} inst.repo=http://{{env_ftp}}/linux/s390x/boot/rel/8.3/ ipv6.disable=1" --location /rhcos-install --qemu-commandline="-drive if=none,id=ignition,format=raw,file=/var/lib/libvirt/images/rhel83.iso,readonly=on -device virtio-blk,serial=ignition,drive=ignition" --noautoconsole
  when: bastion_check.failed == true

- name: README - Pausing for 60 minutes for you to complete the bastion installation of rhel OS with your specific installation's requirements. Please go to your kvm host at https://your-kvm-host-ip-address-here:9090 to complete installation. Once you see the login prompt on the bastion's terminal, come back here and press "ctrl+c" and then "c" on your localhost terminal where you are seeing this message.
  tags: kvm_host, bastionvm
  pause:
    minutes: 60
  when: bastion_check.failed == true