---

#Uncomment once we have a RHEL license
#- name: download RHEL ISO image to KVM
#  get_url:
#      url: {{ RHEL ISO URL }}
#      dest: /var/lib/libvirt/images/rhcos-qemu.s390x.qcow2
#      mode: '0775'

  - name: virtualize bastion server
    command: qemu-img create -f qcow2 -b /var/lib/libvirt/images/rhcos-qemu.s390x.qcow2 /var/lib/libvirt/images/bastion.qcow2 30G

  - name: start bastion install
    command: virt-install --connect qemu:///system --name bastion --memory 8192 --vcpus 4 --disk size=30 --cdrom /var/lib/libvirt/images/rhel82.iso --accelerate --import --network network=macvtap-net --extra-args "ip=9.60.87.139::9.60.86.1:255.255.254.0:bastion::none nameserver=9.60.70.82" --location /rhcos-install --qemu-commandline="-drive if=none,id=ignition,format=raw,file=/var/lib/libvirt/images/rhel82.iso,readonly=on -device virtio-blk,serial=ignition,drive=ignition" --noautoconsole

  - name: wait for bastion to install
    wait:
      minutes: 8