---

- name: Install CoreOS on control nodes
  tags: create_control_nodes
  command: |
    virt-install \
    --name {{env.cluster.nodes.control.vm_name[i]}} \
    --disk pool=default,size={{ env.cluster.nodes.control.disk_size }}  \
    --ram {{env.cluster.nodes.control.ram}} \
    --cpu host \
    --vcpus {{env.cluster.nodes.control.vcpu}} \
    --network network={{env.bridge_name}} \
    --location {{ env.z.lpar.storage_group.pool_path }},kernel=rhcos-live-kernel-s390x,initrd=rhcos-live-initramfs.s390x.img \
    --extra-args "rd.neednet=1 coreos.inst=yes coreos.inst.install_dev=vda coreos.live.rootfs_url=http://{{env.bastion.networking.ip}}:8080/bin/rhcos-live-rootfs.s390x.img ip={{env.cluster.nodes.control.ip[i]}}::{{env.z.lpar.networking.gateway}}:{{env.z.lpar.networking.subnetmask}}:{{env.cluster.nodes.control.hostname[i]}}::none:1500 nameserver={{env.cluster.networking.nameserver}} {{ ('--nameserver=' + env.cluster.networking.nameserver2) if env.cluster.networking.nameserver2 is defined else '' }} coreos.inst.ignition_url=http://{{env.bastion.networking.ip}}:8080/ignition/master.ign" \
    --graphics none \
    --wait=-1 \
    --noautoconsole 
  with_sequence: start=0 end={{(env.cluster.nodes.control.hostname | length) - 1}} stride=1
  loop_control:
    extended: yes
    index_var: i