---

- name: Load in variables from env.yaml
  tags: control
  include_vars: env.yaml

- name: check if control-0 already exists
  tags: control
  community.libvirt.virt:
    name: control-0
    command: status
  register: control_0_check
  ignore_errors: yes

- name: print status of control-0
  tags: control
  debug: 
    var: control_0_check

- name: check if control-1 already exists
  tags: control
  community.libvirt.virt:
    name: control-1
    command: status
  register: control_1_check
  ignore_errors: yes

- name: print status of control-1
  tags: control
  debug: 
    var: control_1_check

- name: check if control-2 already exists
  tags: control
  community.libvirt.virt:
    name: control-2
    command: status
  register: control_2_check
  ignore_errors: yes

- name: print status of control-2
  tags: control
  debug: 
    var: control_2_check

- name: install CoreOS on control-0 node
  tags: control
  command: |
    virt-install --name control-0
    --disk size=100 --ram 16000 --cpu host --vcpus 4 
    --os-type linux --os-variant rhel8.0 
    --network network=macvtap-net 
    --location /var/lib/libvirt/images,kernel=rhcos-live-kernel-s390x,initrd=rhcos-live-initramfs.s390x.img 
    --extra-args "rd.neednet=1 coreos.inst=yes coreos.inst.install_dev=vda coreos.live.rootfs_url=http://{{env_ip_bastion}}:8080/bin/rhcos-live-rootfs.s390x.img ip={{env_ip_control_0}}::{{env_default_gateway}}:{{env_netmask}}:control-0:enc1:none:1500 nameserver={{env_ip_bastion}} coreos.inst.ignition_url=http://{{env_ip_bastion}}:8080/ignition/master.ign" 
    --noautoconsole --wait=-1
  when: control_0_check.failed == true
  
- name: pause 15 minutes
  tags: control
  pause:
    minutes: 15
  when: control_0_check.failed == true
  
- name: install CoreOS on control-1 node
  tags: control
  command: |
    virt-install --name control-1
    --disk size=100 --ram 16000 --cpu host --vcpus 4 
    --os-type linux --os-variant rhel8.0 
    --network network=macvtap-net 
    --location /var/lib/libvirt/images,kernel=rhcos-live-kernel-s390x,initrd=rhcos-live-initramfs.s390x.img 
    --extra-args "rd.neednet=1 coreos.inst=yes coreos.inst.install_dev=vda coreos.live.rootfs_url=http://{{env_ip_bastion}}:8080/bin/rhcos-live-rootfs.s390x.img ip={{env_ip_control_1}}::{{env_default_gateway}}:{{env_netmask}}:control-1:enc1:none:1500 nameserver={{env_ip_bastion}} coreos.inst.ignition_url=http://{{env_ip_bastion}}:8080/ignition/master.ign" 
    --noautoconsole --wait=-1
  when: control_1_check.failed == true

- name: pause 15 minutes
  tags: control
  pause:
    minutes: 15
  when: control_1_check.failed == true

- name: install CoreOS on control-2 node
  tags: control
  command: |
    virt-install --name control-2
    --disk size=100 --ram 16000 --cpu host --vcpus 4 
    --os-type linux --os-variant rhel8.0 
    --network network=macvtap-net 
    --location /var/lib/libvirt/images,kernel=rhcos-live-kernel-s390x,initrd=rhcos-live-initramfs.s390x.img 
    --extra-args "rd.neednet=1 coreos.inst=yes coreos.inst.install_dev=vda coreos.live.rootfs_url=http://{{env_ip_bastion}}:8080/bin/rhcos-live-rootfs.s390x.img ip={{env_ip_control_2}}::{{env_default_gateway}}:{{env_netmask}}:control-2:enc1:none:1500 nameserver={{env_ip_bastion}} coreos.inst.ignition_url=http://{{env_ip_bastion}}:8080/ignition/master.ign" 
    --noautoconsole --wait=-1
  when: control_2_check.failed == true

- name: pause 45 minutes to wait for bootkube.service to complete connecting control nodes. See README for more information.
  tags: control
  pause:
    minutes: 45
  when: control_2_check.failed == true
