---

- name: Load in variables from env.yaml
  tags: control
  include_vars: env.yaml

- name: check if control-0 already exists
  tags: control
  community.libvirt.virt:
    name: "{{ env_control_0_name }}"
    command: status
  register: control_0_check
  ignore_errors: yes

- name: print status of control-0
  tags: control
  debug: 
    var: control_0_check

- name: check if control-1 already exists
  tags: control
  community.libvirt.virt:
    name: "{{ env_control_1_name }}"
    command: status
  register: control_1_check
  ignore_errors: yes

- name: print status of control-1
  tags: control
  debug: 
    var: control_1_check

- name: check if control-2 already exists
  tags: control
  community.libvirt.virt:
    name: "{{ env_control_2_name }}"
    command: status
  register: control_2_check
  ignore_errors: yes

- name: print status of control-2
  tags: control
  debug: 
    var: control_2_check

- name: install CoreOS on control-0 node
  tags: control
  command: |
    virt-install \
    --name {{env_control_0_name}} \
    --disk size={{env_cont_disk_size}} \
    --ram {{env_cont_ram}} \
    --cpu {{env_cont_cpu}} \
    --vcpus {{env_cont_vcpu}} \
    --os-type linux \
    --os-variant rhel{{env_cont_os_variant}} \
    --network network=macvtap-net \
    --location /var/lib/libvirt/images,kernel=rhcos-live-kernel-s390x,initrd=rhcos-live-initramfs.s390x.img \
    --extra-args "rd.neednet=1 coreos.inst=yes coreos.inst.install_dev=vda coreos.live.rootfs_url=http://{{env_ip_bastion}}:8080/bin/rhcos-live-rootfs.s390x.img ip={{env_ip_control_0}}::{{env_default_gateway}}:{{env_netmask}}:{{env_control_0_name}}::none:1500 nameserver={{env_dns_nameserver}} coreos.inst.ignition_url=http://{{env_ip_bastion}}:8080/ignition/master.ign" \
    --graphics none \
    --wait=-1 \
    --noautoconsole 
  when: control_0_check.failed == true
  
- name: install CoreOS on control-1 node
  tags: control
  command: |
    virt-install \
    --name {{env_control_1_name}} \
    --disk size={{env_cont_disk_size}} \
    --ram {{env_cont_ram}} \
    --cpu {{env_cont_cpu}} \
    --vcpus {{env_cont_vcpu}} \
    --os-type linux \
    --os-variant rhel{{env_cont_os_variant}} \
    --network network=macvtap-net \
    --location /var/lib/libvirt/images,kernel=rhcos-live-kernel-s390x,initrd=rhcos-live-initramfs.s390x.img \
    --extra-args "rd.neednet=1 coreos.inst=yes coreos.inst.install_dev=vda coreos.live.rootfs_url=http://{{env_ip_bastion}}:8080/bin/rhcos-live-rootfs.s390x.img ip={{env_ip_control_1}}::{{env_default_gateway}}:{{env_netmask}}:{{env_control_1_name}}::none:1500 nameserver={{env_dns_nameserver}} coreos.inst.ignition_url=http://{{env_ip_bastion}}:8080/ignition/master.ign" \
    --graphics none \
    --wait=-1 \
    --noautoconsole 
  when: control_1_check.failed == true

- name: install CoreOS on control-2 node
  tags: control
  command: |
    virt-install \
    --name {{env_control_2_name}} \
    --disk size={{env_cont_disk_size}} \
    --ram {{env_cont_ram}} \
    --cpu {{env_cont_cpu}} \
    --vcpus {{env_cont_vcpu}} \
    --os-type linux \
    --os-variant rhel{{env_cont_os_variant}} \
    --network network=macvtap-net \
    --location /var/lib/libvirt/images,kernel=rhcos-live-kernel-s390x,initrd=rhcos-live-initramfs.s390x.img \
    --extra-args "rd.neednet=1 coreos.inst=yes coreos.inst.install_dev=vda coreos.live.rootfs_url=http://{{env_ip_bastion}}:8080/bin/rhcos-live-rootfs.s390x.img ip={{env_ip_control_2}}::{{env_default_gateway}}:{{env_netmask}}:{{env_control_2_name}}::none:1500 nameserver={{env_dns_nameserver}} coreos.inst.ignition_url=http://{{env_ip_bastion}}:8080/ignition/master.ign" \
    --graphics none \
    --wait=-1 \
    --noautoconsole 
  when: control_2_check.failed == true