---

- name: Gather facts to get OS family to see which setup script to run
  ansible.builtin.gather_facts:

- name: install Ansible dependencies and packages
  shell: "{{ item }}"
  loop:  
    - ansible-galaxy collection install community.general
    - ansible-galaxy collection install community.crypto
    - ansible-galaxy collection install ansible.posix
    - ansible-galaxy collection install community.libvirt
    - brew install openssh
    - brew install expect
  when: ansible_facts['os_family'] == "Darwin"

- name: install Ansible dependencies and packages
  shell: "{{ item }}"
  loop:
    - ansible-galaxy collection install community.general
    - ansible-galaxy collection install community.crypto
    - ansible-galaxy collection install ansible.posix
    - ansible-galaxy collection install community.libvirt
    - sudo dnf install openssh -y
    - sudo dnf install expect -y
  when: ansible_facts['os_family'] == "RedHat" or ansible_facts['os_family'] == "Debian"
  