---

- name: Destroy bastion for full, skip for partial teardown. Expect ignored errors if it is already destroyed.
  community.libvirt.virt:
    name: "{{ env.bastion.networking.hostname }}"
    command: destroy
  when: bastion_teardown
  ignore_errors: true

- name: Undefine bastion for full, skip for partial teardown. Expect ignored errors if it is already undefined.
  community.libvirt.virt:
    name: "{{ env.bastion.networking.hostname }}"
    command: undefine
  when: bastion_teardown
  ignore_errors: true

- name: Destroy bootstrap. Expect ignored errors if it is already destroyed.
  community.libvirt.virt:
    name: "{{ env.cluster.nodes.bootstrap.hostname }}"
    command: destroy
  ignore_errors: true

- name: Undefine bootstrap. Expect ignored errors if it is already undefined.
  community.libvirt.virt:
    name: "{{ env.cluster.nodes.bootstrap.hostname }}"
    command: undefine
  ignore_errors: true

- name: Destroy running control nodes. Expect ignored errors if some VMs are already destroyed.
  community.libvirt.virt:
    name: "{{ env.cluster.nodes.control.hostname[i] }}"
    command: destroy
  with_sequence: start=0 end={{(env.cluster.nodes.control.hostname | length) - 1}} stride=1
  loop_control:
    extended: yes
    index_var: i
  ignore_errors: true

- name: Undefine remaining control nodes. Expect ignored errors if some VMs are already undefined.
  community.libvirt.virt:
    name: "{{ env.cluster.nodes.control.hostname[i] }}"
    command: undefine
  with_sequence: start=0 end={{(env.cluster.nodes.control.hostname | length) - 1}} stride=1
  loop_control:
    extended: yes
    index_var: i
  ignore_errors: true

- name: Destroy running compute nodes. Expect ignored errors if some VMs are already destroyed.
  community.libvirt.virt:
    name: "{{ env.cluster.nodes.compute.hostname[i] }}"
    command: destroy
  with_sequence: start=0 end={{(env.cluster.nodes.compute.hostname | length) - 1}} stride=1
  loop_control:
    extended: yes
    index_var: i
  ignore_errors: true

- name: Undefine remaining compute nodes. Expect ignored errors if some VMs are already undefined.
  community.libvirt.virt:
    name: "{{ env.cluster.nodes.compute.hostname[i] }}"
    command: undefine
  with_sequence: start=0 end={{(env.cluster.nodes.compute.hostname | length) - 1}} stride=1
  loop_control:
    extended: yes
    index_var: i
  ignore_errors: true

- name: Destroy running infrastructure nodes, if defined. Expect ignored errors if some VMs are already destroyed.
  community.libvirt.virt:
    name: "{{ env.cluster.nodes.infra.hostname[i] }}"
    command: destroy
  with_sequence: start=0 end={{(env.cluster.nodes.infra.hostname | length) - 1}} stride=1
  loop_control:
    extended: yes
    index_var: i
  ignore_errors: true
  when: env.cluster.nodes.infra.hostname is defined

- name: Undefine remaining infrastructure nodes. Expect ignored errors if some VMs are already undefined.
  community.libvirt.virt:
    name: "{{ env.cluster.nodes.infra.hostname[i] }}"
    command: undefine
  with_sequence: start=0 end={{(env.cluster.nodes.infra.hostname | length) - 1}}  stride=1
  loop_control:
    extended: yes
    index_var: i
  ignore_errors: true
  when: env.cluster.nodes.infra.hostname is defined