---

- name: Destroy running VMs. Expect ignored errors if some VMs are already destroyed.
  community.libvirt.virt:
    name: "{{ item }}"
    command: destroy
  loop: "{{ vms }}"
  ignore_errors: yes

- name: Undefine remaining existing VMs. Expect ignored errors if some VMs are already undefined.
  community.libvirt.virt:
    name: "{{ item }}"
    command: undefine
  loop: "{{ vms }}"
  ignore_errors: yes