#For a comprehensive description of each variable, please see documentation here:
#https://ibm.github.io/Ansible-OpenShift-Provisioning/set-variables/ 

env:
  z:
    cpc_name: #X
    hmc:
      host: #X
      auth:
        user: #X
        pass: #X
    lpar:
      name: #X
      description: #X
      access: 
        user: #X
        pass: #X
        root_pass: #X
      ifl:
        count: #X
        initial_memory: #X
        max_memory: #X
        initial_weight: #X
        min_weight: #X
        max_weight: #X
      networking:
        hostname: #X
        ip: #X
        subnetmask: #X
        subnet: #X
        gateway: #X
        nameserver1: #X
#        nameserver2:
        device1: #X
#        device2: 
        nic:
          card1:
            name: #X
            adapter: #X
            port: #X
            dev_num: #X
#          card2: 
#            name:
#            adapter:
#            port:
#            dev_num:
      storage_group:
        name: #X
        type: fcp 
        pool_path: #X
        storage_wwpn:
        - #X
        - #X
        dev_num: #'X'
        vg:
          name: #X
        lv:
          name: #X
        fs:
          name: #X
          type: xfs
        lun_name:
        - #X
        - #X
        - #X 

  ftp:
    ip: #X
    user: #X
    pass: #X
    iso_mount_dir: #X
    cfgs_dir: #X

  redhat:
    username: #X
    password: #X
    pull_secret: #'X'

  bastion:
    create: true
    name: #X
    resources:
      disk_size: 30
      ram: 4096
      swap: 4096
      vcpu: 4
      os_variant: 8.5
    networking:
      ip: #X
      hostname: #X
      subnetmask: #X
      gateway: #X
      nameserver1: #X
#      nameserver2:
      interface: #X
      base_domain: #X
    access:
      user: #X
      pass: #X
      root_pass: #X
      ocp_ssh_key_comment: #X
    options: 
      dns: True
      loadbalancer:
        on_bastion: True
#        public_ip:
#        private_ip:  
    
  cluster:
    networking:
      metadata_name: #X
      base_domain: #X
      nameserver1: #X
#      nameserver2:
      forwarder: #X
    nodes:
      bootstrap:
        disk_size: 120
        ram: 16384
        vcpu: 4
        ip: #X
        hostname: #X
      control:
        disk_size: 120
        ram: 16384
        vcpu: 4
        ip:
        - #X
        - #X
        - #X
        hostname:
        - #X
        - #X
        - #X
      compute:
        disk_size: 120
        ram: 8192
        vcpu: 2
        ip:
        - #X
        - #X
        hostname:
        - #X
        - #X
      infra:
        disk_size: 120
        ram: 16384
        vcpu: 2
        ip:
        - #X
        - #X
        hostname:
        - #X
        - #X

#######################################################################################
# All variables below this point do not need to be changed for a default installation #
#######################################################################################

  language: en_US.UTF-8
  timezone: America/New_York
  root_access: false
  ansible_key_name: ansible-ocpz
  bridge_name: macvtap-net

  pkgs:
    galaxy: [ibm.ibm_zhmc, community.general, community.crypto, ansible.posix, community.libvirt, kwoodson.yedit]
    workstation: [openssh, expect]
    kvm: ['@virt', cockpit-machines, libvirt-devel, virt-top, qemu-kvm, python3-lxml, cockpit]
    bastion: [haproxy, httpd, bind, bind-utils, expect, firewalld, mod_ssl, python3-policycoreutils]

  openshift:
    client: https://mirror.openshift.com/pub/openshift-v4/s390x/clients/ocp/stable/openshift-client-linux.tar.gz
    installer: https://mirror.openshift.com/pub/openshift-v4/s390x/clients/ocp/stable/openshift-install-linux.tar.gz
  
  coreos:
    kernel: https://mirror.openshift.com/pub/openshift-v4/s390x/dependencies/rhcos/4.9/latest/rhcos-4.9.0-s390x-live-kernel-s390x
    initramfs: https://mirror.openshift.com/pub/openshift-v4/s390x/dependencies/rhcos/4.9/latest/rhcos-4.9.0-s390x-live-initramfs.s390x.img
    rootfs: https://mirror.openshift.com/pub/openshift-v4/s390x/dependencies/rhcos/4.9/latest/rhcos-4.9.0-s390x-live-rootfs.s390x.img
  
  install_config:
    api_version: v1
    compute:
      architecture: s390x
      hyperthreading: Enabled
    control:
      architecture: s390x
      hyperthreading: Enabled
    cluster_network:
      cidr: 10.128.0.0/14
      host_prefix: 23
      type: OpenShiftSDN
    service_network: 172.30.0.0/16
    fips: 'false'

#proxy_env:
#  http_proxy: 
#  https_proxy: 
#  no_proxy: 