---

- name: Load in variables from env.yaml
  tags: keymastr,getocp
  include_vars: env.yaml

- name: Check to see if local .ssh directory exists
  tags: keymastr, getocp
  stat:
    path: ~/.ssh
  register: ssh_directory_exists_check

- name: Print results of .ssh directory check
  tags: keymastr,bastion,getocp
  debug:
    var: ssh_directory_exists_check

- name: Create .ssh local directory if it doesn't already exist
  tags: keymastr,getocp
  file:
    path: ~/.ssh
    state: directory
    mode: "0700"
  register: ssh_directory_creation
  when: ssh_directory_exists_check is defined and ssh_directory_exists_check.stat.exists == false

- name: Print results of ssh directory creation
  tags: keymastr,getocp
  debug:
    var: ssh_directory_creation

- name: Check .ssh key pair files exist
  tags: keymastr,getocp
  stat:
    path: ~/.ssh/{{item}}
  register: ssh_key_file_exists_check
  with_items:
    - "id_rsa"
    - "id_rsa.pub"

- name: Print results of ssh key pair files check
  tags: keymastr,getocp
  debug:
    var: ssh_key_file_exists_check.results[1].stat.exists

- name: Generate an OpenSSH keypair with the default values (4096 bits, rsa) and encrypted private key if it doesn't exist already
  tags: keymastr,getocp
  community.crypto.openssh_keypair:
    path: ~/.ssh/id_rsa
    backend: opensshbin
    owner: root
    passphrase: ""
    comment: "{{ env_ssh_ocp_comm }}"
    regenerate: full_idempotence
  register: ssh_ocp
  when: ssh_key_file_exists_check is defined and ssh_key_file_exists_check.results[0].stat.exists == false and ssh_key_file_exists_check.results[1].stat.exists == false 

- name: Print results of ssh key generation
  tags: keymastr,getocp
  debug:
    var: ssh_ocp.public_key
  when: ssh_ocp.changed == true