---

- name: Auto attach RHEL subscription
  tags: attach_subscription
  community.general.redhat_subscription:
    state: present
    username: "{{env.redhat.username}}"
    password: "{{vault.redhat.password}}"
    auto_attach: yes
    force_register: yes