---

- name: Load in variables from env.yaml
  tags: check_dns,dns
  include_vars: env.yaml

- name: Check internal cluster DNS resolution for bastion and its services
  tags: check_dns,dns
  shell: "dig +short {{ item }} | tail -n1"
  loop:
    - "{{ env.hostname.bastion }}.{{ env.install_config.base_domain }}"
    - "api.{{ env.install_config.metadata_name }}.{{ env.install_config.base_domain }}"
    - "api-int.{{ env.install_config.metadata_name }}.{{ env.install_config.base_domain }}"
    - "test.apps.{{ env.install_config.metadata_name }}.{{ env.install_config.base_domain }}"
  register: bastion_lookup
  failed_when: env.ip.bastion != bastion_lookup.stdout
    
- name: Check internal cluster DNS resolution for bootstrap
  tags: check_dns,dns
  shell: "dig +short {{ env.hostname.bootstrap }}.{{ env.install_config.metadata_name }}.{{ env.install_config.base_domain }} | tail -n1"
  register: bootstrap_lookup
  failed_when: env.ip.bootstrap != bootstrap_lookup.stdout

- name: Print results from bootstrap lookup
  tags: check_dns, dns
  debug:
    var: bootstrap_lookup.stdout

- name: Check control nodes DNS resolution
  tags: check_dns,dns
  shell: "dig +short {{ env.hostname.control[i] }}.{{ env.install_config.metadata_name }}.{{ env.install_config.base_domain }}  | tail -n1"
  register: control_lookup
  failed_when: env.ip.control[i] != control_lookup.stdout
  with_sequence: start=0 end={{env.install_config.control.replicas - 1}} stride=1
  loop_control:
    extended: yes
    index_var: i

- name: Check compute nodes DNS resolution
  tags: check_dns,dns
  shell: "dig +short {{ env.hostname.compute[i] }}.{{ env.install_config.metadata_name }}.{{ env.install_config.base_domain }}  | tail -n1"
  register: compute_lookup
  failed_when: env.ip.compute[i] != compute_lookup.stdout
  with_sequence: start=0 end={{env.install_config.compute.replicas - 1}} stride=1
  loop_control:
    extended: yes
    index_var: i

- name: Check external DNS resolution from DNS forwarder
  tags: check_dns,dns
  register: external_dns_check
  failed_when: '"server can" in external_dns_check.stdout'
  command: "nslookup {{ item }}"
  loop: 
    - www.google.com
    - www.ibm.com
    - www.redhat.com