---

- name: check internal cluster DNS resolution
  tags: check_dns,dns
  command: "nslookup {{ item }}"
  register: command_result
  # fail step if the output contains "server can't find"
  failed_when: '"server can" in command_result.stdout'
  with_items:
    - "{{ env_bastion_name }}.{{ env_baseDomain }}"
    - "{{ env_bootstrap_name }}.{{ env_metadata_name }}.{{ env_baseDomain }}"
    - "{{ env_control_0_name }}.{{ env_metadata_name }}.{{ env_baseDomain }}"
    - "{{ env_control_1_name }}.{{ env_metadata_name }}.{{ env_baseDomain }}"
    - "{{ env_control_2_name }}.{{ env_metadata_name }}.{{ env_baseDomain }}"
    - "{{ env_compute_0_name }}.{{ env_metadata_name }}.{{ env_baseDomain }}"
    - "{{ env_compute_1_name }}.{{ env_metadata_name }}.{{ env_baseDomain }}"
    - "api.{{ env_metadata_name }}.{{ env_baseDomain }}"
    - "api-int.{{ env_metadata_name }}.{{ env_baseDomain }}"
    - "test.apps.{{ env_metadata_name }}.{{ env_baseDomain }}"
    
- name: check external DNS resolution from DNS forwarder
  tags: check_dns,dns
  register: command_result
  # fail step if the output contains "server can't find"
  failed_when: '"server can" in command_result.stdout'
  command: "nslookup {{ item }}"
  loop: 
    - www.google.com
    - www.ibm.com
    - www.redhat.com
