---

- name: Check user-input variables in env.yaml for undefined variables
  
- name: fill inventory with user-input vars
  
- name: fill install config with user-input vars

- name: Gather ansible facts about local host

- name: create group_vars files with user-input group names