---    
#- name: create empty list for lun names
#  tags: configure_storage
#  set_fact:
#    lun_list: []

#- name: Fill list of lun names
#  tags: configure_storage
#  set_fact:
#    lun_list: "{{lun_list}} + [ '/dev/mapper/{{ item }}' ]"
#    cacheable: yes
#  loop: "{{ env.z.lpar.storage_group_1.lun_name[1:] }}"

#- name: Create a volume group.
#  tags: configure_storage
#  community.general.lvg:
#    pvs: "{{ lun_list }}"
#    state: present
#    vg: "{{ env.z.lpar.storage_group_1.vg.name }}"   

#- name: Create a logical volume.
#  tags: configure_storage
#  community.general.lvol:
#    vg: "{{ env.z.lpar.storage_group_1.vg.name }}"
#    lv: "{{ env.z.lpar.storage_group_1.lv.name }}" 
#    size: 100%VG

#- name: Create directory for filesystem, if does not exist.
#  tags: configure_storage
#  file:
#    path: "{{ env.z.lpar.storage_group_1.pool_path }}" 
#    state: directory
#    mode: '0755'

#- name: Format the filesystem.
#  tags: configure_storage
#  community.general.filesystem:
#    fstype: "{{env.z.lpar.storage_group_1.fs.type}}"
#    dev: /dev/{{ env.z.lpar.storage_group_1.vg.name }}/{{ env.z.lpar.storage_group_1.lv.name }}

#- name: Mount the logical volume on the filesystem.
#  tags: configure_storage
#  mount:
#    path: "{{ env.z.lpar.storage_group_1.pool_path }}"
#    src: /dev/{{ env.z.lpar.storage_group_1.vg.name }}/{{ env.z.lpar.storage_group_1.lv.name }}
#    fstype: "{{ env.z.lpar.storage_group_1.fs.type }}"
#    state: mounted

- name: Extend the root logical volume to consume all remaining space in the volume group.
  tags: configure_storage
  community.general.lvol:
    vg: rhel_{{env.z.lpar.networking.hostname | lower}}
    lv: root
    size: +100%FREE

- name: Define a new storage pool
  tags: configure_storage
  community.libvirt.virt_pool:
    command: define
    name: "{{ env.z.lpar.storage_group.name }}-vdisk"
    xml: '{{ lookup("template", "vdisk.xml.j2") }}'

- name: Set storage pool to active.
  tags: configure_storage
  community.libvirt.virt_pool:
    name: "{{ env.z.lpar.storage_group.name }}-vdisk"
    state: active

- name: Set storage pool to autostart.
  tags: configure_storage
  community.libvirt.virt_pool:
    name: "{{ env.z.lpar.storage_group.name }}-vdisk"
    autostart: yes