---

- name: Load in variables from env.yaml
  tags: setup,getocp,bastion
  include_vars: env.yaml

- name: create directory bin for mirrors
  tags: getocp,bastion
  file:
    path: /var/www/html/bin
    state: directory
    mode: '0755'

- name: get ocp kernel
  tags: getocp,bastion
  get_url:
    url: https://mirror.openshift.com/pub/openshift-v4/s390x/dependencies/rhcos/latest/latest/rhcos-live-kernel-s390x
    dest: /var/www/html/bin
    mode: '0755'
    force: yes

- name: get ocp initramfs
  tags: getocp,bastion
  get_url:
    url: https://mirror.openshift.com/pub/openshift-v4/s390x/dependencies/rhcos/latest/latest/rhcos-live-initramfs.s390x.img
    dest: /var/www/html/bin
    mode: '0755'
    force: yes
 
- name: get ocp rootfs
  tags: getocp,bastion
  get_url:
    url: https://mirror.openshift.com/pub/openshift-v4/s390x/dependencies/rhcos/latest/latest/rhcos-live-rootfs.s390x.img
    dest: /var/www/html/bin
    mode: '0755'
    force: yes

- name: create OCP download landing directory
  tags: getocp,bastion
  file: 
    path: /ocpinst/
    state: directory

- name: Unzip OCP Client
  tags: getocp,bastion
  ansible.builtin.unarchive:
    src: https://mirror.openshift.com/pub/openshift-v4/s390x/clients/ocp/stable/openshift-client-linux.tar.gz
    dest: /ocpinst/
    remote_src: yes

- name: Unzip OCP Installer
  tags: getocp,bastion
  ansible.builtin.unarchive:
    src: https://mirror.openshift.com/pub/openshift-v4/s390x/clients/ocp/stable/openshift-install-linux.tar.gz
    dest: /ocpinst/
    remote_src: yes

- name: Copy kubectl file
  tags: getocp,bastion
  ansible.builtin.copy:
    src: /ocpinst/kubectl
    dest: /usr/local/bin/kubectl
    remote_src: yes
    owner: root
    group: root
    mode: '0755'

- name: Copy oc file
  tags: getocp,bastion
  ansible.builtin.copy:
    src: /ocpinst/oc
    dest: /usr/local/bin/oc
    remote_src: yes
    owner: root
    group: root
    mode: '0755'

- name: Copy openshift-install file
  tags: getocp,bastion
  ansible.builtin.copy:
    src: /ocpinst/openshift-install
    dest: /usr/local/bin/openshift-install
    remote_src: yes
    owner: root
    group: root
    mode: '0755'

- name: check to see if ocp_ssh_pub file exists
  tags: getocp,bastion
  stat:
    path: roles/get-ocp/files/ocp_ssh_pub
  register: ocp_ssh_pub

- name: delete ocp_ssh_pub file
  tags: getocp, bastion
  file:
    state: absent
    path: roles/get-ocp/files/ocp_ssh_pub
  when: ocp_ssh_pub.stat.exists == true
  register: ocp_ssh_pub_del

- name: create ocp_ssh_pub if it needs to be
  file:
    path: roles/get-ocp/files/ocp_ssh_pub
    mode: '0755'
    state: touch
  when: ocp_ssh_pub_del.changed == true or ocp_ssh_pub.stat.exists == false

- name: Fetch ssh key from bastion for use in install-config
  tags: getocp,bastion
  ansible.builtin.fetch:
    src: ~/.ssh/id_rsa.pub
    dest: roles/get-ocp/files/ocp_ssh_pub
    flat: yes

- name: Use template file to create install-config
  tags: setup,getocp
  template:
    src: install-config.yaml.j2
    dest: /ocpinst/install-config.yaml
    force: yes
    backup: yes

- name: Create Manifests
  tags: getocp,bastion
  command: /ocpinst/openshift-install create manifests --dir=/ocpinst/
  become: yes
  
- name: Set mastersSchedulable parameter to False
  tags: getocp,bastion
  replace:
    path: /ocpinst/manifests/cluster-scheduler-02-config.yml
    regexp: ': true'
    replace: ': false'

- name: Create Ignition files
  tags: getocp,bastion
  command: /ocpinst/openshift-install create ignition-configs --dir=/ocpinst/
  become: yes

- name: create Ignition directory on webserver
  tags: getocp,bastion
  file: 
    path: /var/www/html/ignition
    state: directory

- name: Copy bootstrap Ignition file to web server
  tags: getocp,bastion
  copy:
    src: /ocpinst/bootstrap.ign
    dest: /var/www/html/ignition
    remote_src: yes
    mode: '775'

- name: Copy control plane Ignition file to web server
  tags: getocp,bastion
  copy:
    src: /ocpinst/master.ign
    dest: /var/www/html/ignition
    remote_src: yes
    mode: '775'

- name: Copy worker Ignition file to web server
  tags: getocp,bastion
  copy:
    src: /ocpinst/worker.ign
    dest: /var/www/html/ignition
    remote_src: yes
    mode: '775'
