---

- name: Load in variables
  tags: ssh_copy_id, ssh
  include_vars: "{{item}}"
  with_items:
    - env.yaml
    - roles/ssh_copy_id/vars/path_to_key_pair.yaml

- name: Get ansible.pub key for check in next task
  tags: ssh_copy_id, ssh
  set_fact:
    ans_pub_key: "{{ lookup('file', '~/.ssh/ansible.pub') }}"

- name: Print Ansible public key
  tags: ssh_copy_id, ssh
  debug:
    msg: "{{ ans_pub_key }}"

- name: Delete SSH key from known hosts if it already exists for idempotency
  tags: ssh_copy_id, ssh
  lineinfile:
    path: "~/.ssh/known_hosts"
    line: "{{ ssh_target_ip }}"
    state: absent
  delegate_to: localhost

- name: Use template file to create expect script
  tags: ssh_copy_id, ssh
  template:
    src: ssh-copy-id.exp.j2
    dest: roles/ssh_copy_id/files/ssh-copy-id-expect-pass.exp
    force: yes

- name: Copy SSH ID to remote host with pre-provided password
  tags: ssh_copy_id, ssh
  command: "expect roles/ssh_copy_id/files/ssh-copy-id-expect-pass.exp"
  register: ssh_copy

- name: Print results of copying ssh id to remote host.
  tags: ssh_copy_id, ssh
  debug:
    var: ssh_copy

- name: Delete templated expect script
  tags: ssh_copy_id, ssh
  file:
    path: roles/ssh_copy_id/files/ssh-copy-id-expect-pass.exp
    state: absent

- name: Re-create ssh-copy-id files folder
  tags: ssh_copy_id, ssh
  file:
    path: roles/ssh_copy_id/files/
    state: directory