---

- name: distribute the ssh key to the remote hosts
  tags: keymastr
  shell: "/usr/local/bin/sshpass -p \"{{remote_machine_password}}\" ssh-copy-id -o StrictHostKeyChecking=no -i ~/.ssh/{{ssh_key_filename}}.pub -p {{ remote_host_ip}}.22 \"{{remote_machine_username}}@{{ remote_host_ip }}\""
  register: ssh_copy_id_execution
  failed_when: ssh_copy_id_execution.rc != 0

- name: Print results of copying ssh id to remote host.
  tags: keymastr
  debug:
    var: ssh_copy_id_execution
