---

- name: distribute the ssh key to the remote hosts
  shell: "/usr/local/bin/sshpass -p \"{{ssh_target_password}}\" ssh-copy-id -o StrictHostKeyChecking=no -i ~/.ssh/{{ssh_key_filename}}.pub -p {{ ssh_target_ip}}.22 \"{{ssh_target_username}}@{{ ssh_target_ip }}\""
  register: ssh_copy_id_execution
  failed_when: ssh_copy_id_execution.rc != 0

- name: Print results of copying ssh id to remote host.
  debug:
    var: ssh_copy_id_execution
