---

- name: Populate inventory with KVM host, bastion and bootstrap IP addresses
  tags: set_inventory
  blockinfile:
    path: "{{ inventory_file }}"
    marker: "#{mark} ansible managed block from set_inventory role"
    marker_begin: "start of"
    marker_end: "end of"
    block: |
      [ftp]
      {{ vault.ftp.ip }} ansible_user={{ env.ftp.user }}

      [kvm_host]
      {{ env.z.lpar.networking.hostname }} ansible_host={{vault.z.lpar.networking.ip}} ansible_user={{env.z.lpar.access.user}} ansible_become_password={{vault.z.lpar.access.pass}}

      [bastion]
      {{env.bastion.networking.hostname}} ansible_host={{vault.bastion.networking.ip}} ansible_user={{env.bastion.access.user}} ansible_become_password={{vault.bastion.access.pass}}
    state: present

- name: Add path to Ansible private key
  tags: set_inventory
  lineinfile:
    line: "private_key_file=~/.ssh/{{ env.ansible_key_name }}"
    regexp: "private_key_file"
    state: present

- name: check inventory setup
  tags: set_inventory
  command: ansible-inventory --list
  register: inv_check
  failed_when: inv_check.rc != 0

- name: Gather facts to re-read inventory after changes made to inventory
  tags: set_inventory
  ansible.builtin.gather_facts:

- name: Refresh inventory
  tags: set_inventory
  meta: refresh_inventory