---

- name: Template out inventory with workstation, FTP, KVM host, and bastion information
  tags: set_inventory
  template:
    src: hosts.j2
    dest: "{{ inventory_dir }}/hosts"
    force: yes

- name: Add path to Ansible private key
  tags: set_inventory
  lineinfile:
    line: "private_key_file=~/.ssh/{{ env.ansible_key_name }}"
    path: "{{ ansible_config_file }}"
    regexp: "private_key_file"
    state: present

- name: check inventory setup
  tags: set_inventory
  command: ansible-inventory --list
  register: inv_check
  failed_when: inv_check.rc != 0

- name: Gather facts to re-read inventory after changes made to inventory
  tags: set_inventory
  ansible.builtin.gather_facts:

- name: Refresh inventory
  tags: set_inventory
  meta: refresh_inventory
