---

- name: Load in variables from env.yaml
  tags: setup
  include_vars: env.yaml

- name: Populate inventory file with ip variables from env.yaml
  tags: setup
  blockinfile:
    path: inventory
    block: |
      [kvm_host]
      {{ env_ip_kvm_host }}

      [bastion]
      {{ env_ip_bastion }}

      [bootstrap]
      {{ env_ip_bootstrap }}

      [control_nodes]
      {{ env_ip_control_0 }}
      {{ env_ip_control_1 }}
      {{ env_ip_control_2 }}

      [compute_nodes]
      {{env_ip_compute_0}}
      {{env_ip_compute_1}}
    state: present

- name: check inventory setup
  tags: setup
  command: ansible-inventory --list
  register: inv_check
  failed_when: inv_check.rc != 0

- name: Gather facts to re-read inventory after changes made to inventory
  tags: setup
  ansible.builtin.gather_facts:

- name: Refresh inventory
  tags: setup
  meta: refresh_inventory

- name: fill ansible.cfg with provided variable ansible ssh key file name
  tags: setup
  ansible.builtin.lineinfile:
    path: ansible.cfg
    insertafter: '\[defaults\]'
    line: private_key_file=~/.ssh/{{ env_ssh_ans_name }}

- name: fill ansible.cfg with default ansible password
  tags: setup
  ansible.builtin.lineinfile:
    path: ansible.cfg
    insertafter: '\[defaults\]'
    line: ansible_password={{env_vm_root_passwd}}

- name: fill ansible.cfg with default ansible user
  tags: setup
  ansible.builtin.lineinfile:
    path: ansible.cfg
    insertafter: '\[defaults\]'
    line: remote_user=root

- name: delete ocp_ssh_pub file if it exists already to ensure idempotence
  tags: setup
  file:
    state: absent
    path: roles/get-ocp/files/ocp_ssh_pub

- name: create ocp_ssh_pub if it needs to be
  tags: setup
  file:
    path: roles/get-ocp/files/ocp_ssh_pub
    mode: '0755'
    state: touch

- name: comment out auto-attach rhel subscription line in main.yaml if requested with env.yaml auto_attach_rhel_sub boolean
  tags: setup
  replace:
    path: main.yaml
    regexp: "- attach_subscription"
    replace: "#- attach_subscription"
  when: not auto_attach_rhel_sub

- name: Comment out DNS setup role in main.yaml if requested with env.yaml env_dns_on_bastion boolean
  tags: setup
  replace:
    regexp: "- dns"
    path: main.yaml
    replace: "#- dns"
  when: not env_dns_on_bastion