---

- name: enable named
  tags: dns,bastion
  ansible.builtin.systemd:
      name: named
      enabled: yes

- name: start named
  tags: dns,bastion
  ansible.builtin.systemd:
      name: named
      state: started

- name: Copy named.conf file to bastion
  tags: dns,bastion
  ansible.builtin.copy:
    src: named.conf
    dest: /etc/
    owner: root
    group: root
    mode: '0755'
    backup: yes

- name: Copy distribution.db file to bastion
  tags: dns,bastion
  ansible.builtin.copy:
    src: distribution.db
    dest: /var/named
    owner: named
    group: named
    mode: '0755'
    backup: yes

- name: Copy distribution.rev file to bastion
  tags: dns,bastion
  ansible.builtin.copy:
    src: distribution.rev
    dest: /var/named
    owner: named
    group: named
    mode: '0755'
    backup: yes

- name: restart named to update changes made to DNS
  tags: dns,bastion
  ansible.builtin.systemd:
      name: named
      state: restarted