---

- name: Load in variables from env.yaml
  tags: dns
  include_vars: env.yaml

- name: Enable named
  tags: dns
  ansible.builtin.systemd:
      name: named
      enabled: yes

- name: Start named
  tags: dns
  ansible.builtin.systemd:
      name: named
      state: started

- name: Split IP addresses for use in templates
  tags: dns
  set_fact: 
    bastion_split_ip: "{{ env.ip.bastion.split('.') }}"
    bootstrap_split_ip: "{{ env.ip.bootstrap.split('.') }}"

- name: Template named.conf file to bastion
  tags: dns
  template:
    src: dns-named.conf.j2
    dest: /etc/named.conf
    owner: root
    group: root
    mode: '0755'
    backup: yes

- name: Template DNS forwarding file to bastion
  tags: dns
  template:
    src: dns.db.j2
    dest: /var/named/{{env.install_config.metadata_name}}.db
    owner: named
    group: named
    mode: '0755'
    backup: yes

- name: Add control nodes to DNS forwarding file on bastion
  tags: dns
  lineinfile:
    path: /var/named/{{env.install_config.metadata_name}}.db
    insertafter: "entries for the control nodes"
    line: "{{ env.hostname.control[i] }}.{{ env.install_config.metadata_name }}.{{ env.install_config.base_domain }}. IN A {{ env.ip.control[i] }}"
  with_sequence: start=0 end={{env.install_config.control.replicas - 1}} stride=1
  loop_control:
    extended: yes
    index_var: i

- name: Add compute nodes to DNS forwarding file on bastion
  tags: dns
  lineinfile:
    path: /var/named/{{env.install_config.metadata_name}}.db
    insertafter: "entries for the compute nodes"
    line: "{{ env.hostname.compute[i] }}.{{ env.install_config.metadata_name }}.{{ env.install_config.base_domain }}. IN A {{ env.ip.compute[i] }}"
  with_sequence: start=0 end={{env.install_config.compute.replicas - 1}} stride=1
  loop_control:
    extended: yes
    index_var: i

- name: Template DNS reverse lookup file to bastion
  tags: dns
  template:
    src: dns.rev.j2
    dest: /var/named/{{env.install_config.metadata_name}}.rev
    owner: named
    group: named
    mode: '0755'
    backup: yes

- name: Add control nodes to DNS reverse lookup file on bastion
  tags: dns
  lineinfile:
    path: /var/named/{{env.install_config.metadata_name}}.rev
    insertafter: "PTR Record IP address to Hostname"
    line: "{{ env.ip.control[i].split('.').3 }}     IN      PTR     {{ env.hostname.control[i] }}.{{ env.install_config.metadata_name }}.{{ env.install_config.base_domain }}."
  with_sequence: start=0 end={{env.install_config.control.replicas - 1}} stride=1
  loop_control:
    extended: yes
    index_var: i

- name: Add compute nodes to DNS reverse lookup file on bastion
  tags: dns
  lineinfile:
    path: /var/named/{{env.install_config.metadata_name}}.rev
    insertafter: "PTR Record IP address to Hostname"
    line: "{{ env.ip.compute[i].split('.').3 }}     IN      PTR     {{ env.hostname.compute[i] }}.{{ env.install_config.metadata_name }}.{{ env.install_config.base_domain }}."
  with_sequence: start=0 end={{env.install_config.compute.replicas - 1}} stride=1
  loop_control:
    extended: yes
    index_var: i

- name: Restart named to update changes made to DNS
  tags: dns
  ansible.builtin.systemd:
      name: named
      state: restarted