---

- name: Add ports to firewalld
  tags: firewall,bastion
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
  loop:
    - 8080/tcp
    - 80/tcp
    - 443/tcp
    - 4443/tcp
    - 6443/tcp
    - 22623/tcp
    - 53/udp

- name: Permit traffic in default zone for http and https
  tags: firewall,bastion
  ansible.posix.firewalld:
    service: "{{ item }}"
    permanent: yes
    state: enabled
  loop:
    - http
    - https

- name: Ensure the default Apache port is 8080
  tags: httpconf,bastion.firewall
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    search_string: 'Listen 80'
    line: 'Listen 8080'
    backup: yes

- name: Ensure the SSL default port is 4443
  tags: httpconf,bastion,firewall
  replace:
    path: /etc/httpd/conf.d/ssl.conf
    regexp: '^Listen 443 https'
    replace: 'Listen 4443 https'
    backup: yes

- name: reload firewalld to reflect changes
  tags: firewall,bastion
  systemd:
    name: firewalld
    state: reloaded

- name: restart httpd
  tags: firewall,bastion
  service:
    name: httpd
    state: restarted