---

- name: Allow all access to tcp port 8080
  tags: firewall,bastion
  ansible.posix.firewalld:
    port: 8081/tcp
    permanent: yes
    state: enabled

- name: Allow all access to tcp port 80
  tags: firewall,bastion
  ansible.posix.firewalld:
    port: 80/tcp
    permanent: yes
    state: enabled

- name: Allow all access to tcp port 443
  tags: firewall,bastion
  ansible.posix.firewalld:
    port: 443/tcp
    permanent: yes
    state: enabled

- name: Allow all access to tcp port 4443
  tags: firewall,bastion
  ansible.posix.firewalld:
    port: 4443/tcp
    permanent: yes
    state: enabled

- name: Permit traffic in default zone for http
  tags: firewall,bastion
  ansible.posix.firewalld:
    service: http
    permanent: yes
    state: enabled

- name: Permit traffic in default zone for https
  tags: firewall,bastion
  ansible.posix.firewalld:
    service: https
    permanent: yes
    state: enabled

- name: restart httpd
  service:
    name: httpd
    state: restarted