---

- name: Installing required packages
  ansible.builtin.package:
    name: 
      - "{{ packages[0] | default(omit) }}"
      - "{{ packages[1] | default(omit) }}"
      - "{{ packages[2] | default(omit) }}"
      - "{{ packages[3] | default(omit) }}"
      - "{{ packages[4] | default(omit) }}"
      - "{{ packages[5] | default(omit) }}"
      - "{{ packages[6] | default(omit) }}"
      - "{{ packages[7] | default(omit) }}"
    state: latest
    update_cache: yes