---
- name: get host os family
  vars:
    host_os_family: "{{ ansible_facts['os_family'] }}"

- name: Installing required packages on Linux machine
  ansible.builtin.package:
    name: 
      - "{{ packages[0] }}"
      - "{{ packages[1] | default(omit) }}"
      - "{{ packages[2] | default(omit) }}"
      - "{{ packages[3] | default(omit) }}"
      - "{{ packages[4] | default(omit) }}"
      - "{{ packages[5] | default(omit) }}"
      - "{{ packages[6] | default(omit) }}"
      - "{{ packages[7] | default(omit) }}"
    state: present
    update_cache: yes
  when:  host_os_family == "RedHat" or host_os_family == "Debian"

- name: Installing required packages on Mac machine
  community.general.homebrew:
    name: 
      - "{{ packages[0] }}"
      - "{{ packages[1] | default(omit) }}"
      - "{{ packages[2] | default(omit) }}"
      - "{{ packages[3] | default(omit) }}"
      - "{{ packages[4] | default(omit) }}"
      - "{{ packages[5] | default(omit) }}"
      - "{{ packages[6] | default(omit) }}"
      - "{{ packages[7] | default(omit) }}"
    state: present
    update_homebrew: yes
  when:  host_os_family == "Darwin"