---

- name: Installing required packages on "{{ ansible_facts['host'] }}"
  ansible.builtin.package:
    name: 
      - "{{ packages[0] }}"
      - "{{ packages[1] | default(omit) }}"
      - "{{ packages[2] | default(omit) }}"
      - "{{ packages[3] | default(omit) }}"
      - "{{ packages[4] | default(omit) }}"
      - "{{ packages[5] | default(omit) }}"
      - "{{ packages[6] | default(omit) }}"
      - "{{ packages[6] | default(omit) }}"
    state: present
    update_cache: yes
