---

- name: print the list of packages to be installed and updated
  tags: pkg
  debug:
    var: packages

- name: installing required packages
  tags: pkg
  ansible.builtin.package:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop: "{{ packages }}"