---

- name: Change permissive domain for httpd
  tags: selinux,httpconf,bastion
  selinux_permissive:
    name: httpd_t
    permissive: true

- name: enable httpd
  tags: httpconf,bastion
  systemd:
    name: httpd
    enabled: yes

- name: restart httpd
  service:
    name: httpd
    state: restarted