---

- name: Change permissive domain for httpd
  tags: selinux,httpconf
  selinux_permissive:
    name: httpd_t
    permissive: true

- name: enable httpd
  tags: httpconf
  systemd:
    name: httpd
    enabled: yes

- name: Ensure the default Apache port is 8080
  tags: httpconf
  replace:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^Listen 80'
    replace: 'Listen 8080'
    backup: yes
  notify: restart httpd

- name: Ensure the SSL default port is 4443
  tags: httpconf
  replace:
    path: /etc/httpd/conf.d/ssl.conf
    regexp: '^Listen 443 https'
    replace: 'Listen 4443 https'
    backup: yes
  notify: restart httpd
