---

- name: enable httpd
  systemd:
    name: httpd
    enabled: yes

- name: Ensure the default Apache port is 8080
  replace:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^Listen 80'
    replace: 'Listen 8080'
    backup: yes
  notify: restart httpd

- name: Ensure the SSL default port is 4443
  replace:
    path: /etc/httpd/conf.d/ssl.conf
    regexp: '^Listen 443 https'
    replace: 'Listen 4443 https'
    backup: yes
  notify: restart httpd
