---

- name: Change permissive domain for httpd
  tags: selinux,httpd,bastion
  selinux_permissive:
    name: httpd_t
    permissive: true

- name: enable httpd
  tags: httpd,bastion
  systemd:
    name: httpd
    enabled: yes

- name: restart httpd
  tags: httpd,bastion
  service:
    name: httpd
    state: restarted