---

#- name: install httpd
#    dnf:
#      name: httpd
#      state: latest
  
- name: Ensure the default Apache port is 8080
  replace:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^Listen 80'
    replace: 'Listen 8080'
    backup: yes

- name: Ensure the SSL default port is 4443
  replace:
    path: /etc/httpd/conf.d/ssl.conf
    regexp: '^Listen 443 https'
    replace: 'Listen 4443 https'
    backup: yes

- name: restart httpd to reflect changes to port
  service:
    name: httpd
    state: restarted

#- name: Allow all access to tcp port 8080
#  community.general.ufw:
#    rule: allow
#    port: '8080'
#    proto: tcp
#
#- name: Allow all access to tcp port 80
#  community.general.ufw:
#    rule: allow
#    port: '80'
#    proto: tcp
#
#- name: Allow all access to tcp port 443
#  community.general.ufw:
#    rule: allow
#    port: '443'
#    proto: tcp
#
#- name: Allow all access to tcp port 4443
#  community.general.ufw:
#    rule: allow
#    port: '4443'
#    proto: tcp

- name: create directory bin for mirrors
  file:
    path: /var/www/html/bin
    state: directory
    mode: '0755'

- name: create directory bootstrap for mirrors
  file:
    path: /var/www/html/bootstrap
    state: directory
    mode: '0755'

- name: get mirrors 1
  get_url:
    url: https://mirror.openshift.com/pub/openshift-v4/s390x/dependencies/rhcos/latest/latest/rhcos-live-kernel-s390x
    dest: /var/www/html/bin
    remote_src: yes
    mode: '0755'

- name: get mirrors 2
  get_url:
    url: https://mirror.openshift.com/pub/openshift-v4/s390x/dependencies/rhcos/latest/latest/rhcos-live-initramfs.s390x.img
    dest: /var/www/html/bin
    remote_src: yes
    mode: '0755'
 
- name: get mirrors 3
  get_url:
    url: https://mirror.openshift.com/pub/openshift-v4/s390x/dependencies/rhcos/latest/latest/rhcos-live-rootfs.s390x.img
    dest: /var/www/html/bin
    remote_src: yes
    mode: '0755'

- name: check to make sure httpd is started
  service:
    name: httpd
    state: started

- name: check httpd status
  service:
    state: started
    name: httpd
