- hosts: bastion_server
  become: true
  tasks:

  - name: Set mastersSchedulable parameter to False
    replace:
      path: /ocpinst/manifests/cluster-scheduler-02-config.yml
      regexp: ': true'
      replace: ': false'
  
