---

- name: Load in variables from env.yaml
  tags: get_ocp
  include_vars: env.yaml

- name: Create directory bin for mirrors
  tags: get_ocp
  file:
    path: /var/www/html/bin
    state: directory
    mode: '0755'
 
- name: Check to see if rootfs already exists on bastion
  tags: get_ocp
  stat:
    path: /var/www/html/bin/rhcos-live-rootfs.s390x.img
  register: rootfs_check

- name: Get Red Hat CoreOS rootfs file
  tags: get_ocp
  get_url:
    url: "{{ env.coreos.rootfs }}"
    dest: /var/www/html/bin/rhcos-live-rootfs.s390x.img
    mode: '0755'
    force: yes
  when: rootfs_check.stat.exists == false

- name: Delete OCP download directory for idempotency, because ignition files deprecate after 24 hours.
  tags: get_ocp
  file: 
    path: /ocpinst
    state: absent

- name: Create OCP download directory
  tags: get_ocp
  file: 
    path: /ocpinst/
    state: directory

- name: Unzip OCP client and installer
  tags: get_ocp
  ansible.builtin.unarchive:
    src: "{{ item }}"
    dest: /ocpinst/
    remote_src: yes
  loop:
    - "{{ env.openshift.client }}"
    - "{{ env.openshift.installer }}"

- name: Copy kubectl and oc files to bastion
  tags: get_ocp
  ansible.builtin.copy:
    src: /ocpinst/{{item}}
    dest: /usr/local/bin/{{item}}
    remote_src: yes
    owner: root
    group: root
    mode: '0755'
  loop:
    - kubectl
    - oc

- name: Copy openshift-install file to bastion
  tags: get_ocp
  ansible.builtin.copy:
    src: /ocpinst/openshift-install
    dest: /usr/local/bin/openshift-install
    remote_src: yes
    owner: root
    group: root
    mode: '0755'

- name: Fetch SSH key from bastion for use in template
  tags: getocp,bastion
  ansible.builtin.fetch:
    src: ~/.ssh/id_rsa.pub
    dest: roles/get_ocp/files/ocp_ssh_pub.yaml
    flat: yes

- name: Use template file to create install-config
  tags: get_ocp
  template:
    src: install-config.yaml.j2
    dest: /ocpinst/install-config.yaml
    force: yes
    backup: yes

- name: Create manifests
  tags: get_ocp
  command: /ocpinst/openshift-install create manifests --dir=/ocpinst/
  become: yes
  
- name: Set masters schedulable parameter to false
  tags: get_ocp
  replace:
    path: /ocpinst/manifests/cluster-scheduler-02-config.yml
    regexp: ': true'
    replace: ': false'

- name: Create ignition files
  tags: get_ocp
  command: /ocpinst/openshift-install create ignition-configs --dir=/ocpinst/
  become: yes

- name: create ignition directory on webserver
  tags: get_ocp
  file: 
    path: /var/www/html/ignition
    state: directory

- name: Copy ignition files to web server
  tags: get_ocp
  copy:
    src: /ocpinst/{{ item }}.ign
    dest: /var/www/html/ignition
    remote_src: yes
    mode: '775'
  loop:
    - bootstrap
    - master
    - worker