#Prepare KVM host and create bastion node
- hosts: kvm_host
  become: true
  vars_files: 
    - "{{ inventory_dir }}/group_vars/all.yaml"
  roles:
    - { role: create_bastion, when: env.bastion.create == True }