---

#Create KVM guests
- hosts: kvm_host
  become: true
  gather_facts: false
  vars_files: 
    - ../env.yaml
  roles:
    - prep_kvm_guests
    - create_bootstrap
    - create_control_nodes
    - create_compute_nodes