---

#Prepare and then create the temporary bootstrap node and the control nodes.
- hosts: kvm_host
  become: true
  gather_facts: false
  vars_files: 
    - "{{ inventory_dir }}/group_vars/all.yaml"
  roles:
    - prep_kvm_guests
    - create_bootstrap
    - create_control_nodes

#Wait for bootstrap to connect control plane.
- hosts: bastion
  become: false
  environment:
    KUBECONFIG: "/home/{{ env.bastion.access.user }}/ocpinst/auth/kubeconfig"
  gather_facts: true
  vars_files: 
    - "{{ inventory_dir }}/group_vars/all.yaml"
  roles:
    - wait_for_bootstrap

#Once bootstrapping is complete, create compute nodes.
- hosts: kvm_host
  become: true
  gather_facts: false
  vars_files: 
    - "{{ inventory_dir }}/group_vars/all.yaml"
  roles:
    - create_compute_nodes