---

#Copy SSH key to access KVM host
- hosts: workstation
  connection: local
  become: false
  gather_facts: true
  vars:
    ssh_target: ["{{ env.z.lpar.networking.ip }}","{{ env.z.lpar.access.user }}","{{ env.z.lpar.access.pass }}"]
  vars_files: 
    - ../env.yaml
  roles:
    - ssh_copy_id

#Prepare KVM host and create bastion node
- hosts: kvm_host
  become: true
  vars: 
    packages: "{{ env.pkgs.kvm}}"
  vars_files: 
    - ../env.yaml
  roles:
    - {role: attach_subscription, when: env.redhat.username is defined and env.redhat.password is defined}
    - install_packages
  post_tasks:
    - name: Enable cockpit console
      command: systemctl enable --now cockpit.socket
    - name: Start and enable libvirt
      service:
        name: libvirtd
        enabled: yes
        state: started

- hosts: kvm_host
  become: true
  vars_files: 
    - ../env.yaml
  roles:
    - configure_storage
    - macvtap