---

- hosts: workstation
  tags: workstation
  connection: local
  become: false
  gather_facts: true
  pre_tasks:

    - name: Install required Ansible Galaxy collections.
      command: ansible-galaxy collection install {{ item }}
      loop: "{{ env.pkgs.galaxy }}"
    
    - name: Install YAML edit custom module
      command: ansible-galaxy install kwoodson.yedit

    - name: Get ibm_zhmc collection install location
      shell: ansible-galaxy collection list ibm.ibm_zhmc | grep -i ansible | cut -c 3-
      register: zhmc_path

    - name: Install zhmcclient requirements
      pip:
        requirements: "{{zhmc_path.stdout}}/ibm/ibm_zhmc/requirements.txt"
        executable: pip3
        extra_args: --upgrade

  roles:
    - kwoodson.yedit
    - encrypt_vars

- hosts: workstation
  connection: local
  become: false
  gather_facts: false
  vars_files:
    - ../vault.yaml
  vars:
    - packages: "{{ env.pkgs.workstation }}"
    - ssh_target: [ "{{ vault.ftp.ip }}", "{{ env.ftp.user }}", "{{ vault.ftp.pass }}" ]
  roles:
    - install_packages
    - set_inventory
    - ssh_key_gen
    - ssh_agent
    - ssh_copy_id #to FTP server