---

#Copy SSH key to access bastion
- hosts: workstation
  connection: local
  become: false
  gather_facts: false
  vars_files: 
    - ../vault.yaml
  vars: 
    ssh_target: ["{{ vault.bastion.networking.ip }}","{{ env.bastion.access.user }}","{{ vault.bastion.access.pass }}"]
  roles:
    - ssh_copy_id

#Configure bastion node with essential services
- hosts: bastion
  become: true
  vars:
    packages: "{{ env.pkgs.bastion }}"
  vars_files: 
    - ../vault.yaml
  roles:
    - {role: attach_subscription, when: env.redhat.username is defined and vault.redhat.password is defined}
    - install_packages
    - ssh_ocp_key_gen
    - set_firewall
    - {role: dns, when: env.bastion.options.dns }
    - check_dns
    - { role: haproxy, when: env.bastion.options.loadbalancer }
    - httpd
    - {role: get_ocp, become: false }