---

- hosts: workstation
  tags: workstation
  connection: local
  become: false
  gather_facts: true
  pre_tasks:
  
    - name: Install required Ansible Galaxy collections.
      command: ansible-galaxy collection install {{ item }}
      loop: "{{ env.pkgs.galaxy }}"

    - name: Get ibm_zhmc collection install location
      shell: ansible-galaxy collection list ibm.ibm_zhmc | grep -i ansible | cut -c 3-
      register: zhmc_path

    - name: Install zhmcclient requirements
      pip:
        requirements: "{{zhmc_path.stdout}}/ibm/ibm_zhmc/requirements.txt"
        executable: pip3
        extra_args: --upgrade

- hosts: workstation
  connection: local
  become: false
  gather_facts: false
  vars_files:
    - "{{ inventory_dir }}/group_vars/all.yaml"
  vars:
    - packages: "{{ env.pkgs.workstation }}"
    - ssh_target: [ "{{ env.ftp.ip }}", "{{ env.ftp.user }}", "{{ env.ftp.pass }}" ]
  roles:
    - install_packages
    - set_inventory
    - ssh_key_gen
    - ssh_agent
    - ssh_copy_id #to FTP server