---
- hosts: web-servers
  become: true
  become_method: sudo
  tasks:
  - name: Ensure the PGP key is installed
    apt_key:
      id: AC40B2F7
      url: "http://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x561F9B9CAC40B2F7"

  - name: Ensure https support for apt is installed
    package:
      name: apt-transport-https

  - name: Ensure the passenger apt repository is added
    apt_repository:
      repo: 'deb https://oss-binaries.phusionpassenger.com/apt/passenger raring main'

  - name: Ensure nginx is installed
    package:
      name: nginx-full

  - name: Ensure passenger is installed
    apt:
      name: passenger
      update_cache: yes

  - name: Ensure the nginx configuration file is set
    copy:
      src: /app/config/nginx.conf
      dest: /etc/nginx/nginx.conf

  - name: Ensure nginx is running
    service:
      name: nginx
      state: started



