---

- name: Load in variables
  tags: ssh_copy_id, ssh
  include_vars: "{{inventory_dir}}/group_vars/all.yaml"

- name: Use template file to create expect script
  tags: ssh_copy_id, ssh
  template:
    src: ssh-copy-id.exp.j2
    dest: "/tmp/ssh-copy-id-expect-pass.exp"
    force: yes

- name: Copy SSH ID from jumphost to bastion with pre-provided password
  tags: ssh_copy_id, ssh
  command: "expect /tmp/ssh-copy-id-expect-pass.exp"
  register: ssh_copy

- name: Print results of copying ssh id to remote host
  tags: ssh_copy_id, ssh
  debug:
    var: ssh_copy

- name: Delete templated expect script
  tags: ssh_copy_id, ssh
  file:
    path: "/tmp/ssh-copy-id-expect-pass.exp"
    state: absent
